- .github/workflows/api-prod.yaml
- .github/workflows/api-staging.yaml
Pins the `setup-gcloud` action to the latest commit (`efdd40b`) instead of using `master`. A specific version/tag would be ideal, however there hasn't been a new release for a few months.
N/A
> fix: Pin setup-gcloud action to latest commit

- client/package-lock.json
Bumps `lodash` to 4.17.20 to resolve a vulnerability alert. Includes changes from #16 
- Chore
N/A
> chore(client): Bump lodash to 4.17.20

- client/Dockerfile
Fix issue with Docker NGINX 404 when Explorer URL on the Browser contains a path
Tested manually
> Fix React URL with Paths cause an NGINX 404

- api/Dockerfile
`zeromq` requires native code compilation, but we can't guarantee the availability of prebuilt binaries (e.g. https://github.com/iotaledger/one-click-tangle/issues/45). This PR adds the necessary dependencies to build `zeromq` if necessary. Since including these dependencies increases the image size considerably, we can use a multi-stage build to copy the compiled JS and production dependencies to a fresh container.
Tested building the Docker image locally
> fix(api): Support compiling zeromq in Docker

- client/src/app/components/MessageTree.tsx
Fix tx page unnecessary auto scroll to bottom when the message tree of a selected message changes. 
> Fix message tree jump

- client/src/app/components/chrysalis/Transaction.tsx
- client/src/app/components/chrysalis/TransactionProps.tsx
- client/src/app/routes/chrysalis/Addr.tsx
- client/src/models/api/chrysalis/ITransactionsDetailsResponse.ts
- client/src/services/tangleCacheService.ts
This PR aims to fix two issues on Address page:
1.  #97
2. #166
Test for #97 issue: Navigate to any address page with conflicting transactions ex. `/mainnet/addr/iota1qz2xs449nm04al9pyxvfl9mgaj359fj06y3awetg7c6vjd0jjm39cyuku8a`
Test for #166 issue: Navigate to any address page with more than 10 history transactions and go trough history transactions using pagination
> Fix: duplicated history tsx

- client/src/app/routes/IdentityResolver.tsx
Restored changes lost in a recent merge of `dev`. This fixes the display of the document in the identity resolver to only display the content of `doc`,
Seems to have been caused here: https://github.com/iotaledger/explorer/blob/61edccc3785c9c6d2dc90604a5b0edac62aeca94/client/src/app/routes/IdentityResolver.tsx
Tested locally.
> Fix: identity doc display

- client/src/app/routes/Visualizer.scss
- client/src/app/routes/Visualizer.tsx
- client/src/app/routes/VisualizerState.ts
Added a pause button to visualiser and functionality to pause() and resume() the renderer on button toggle.
Closes: https://github.com/iotaledger/explorer/issues/181
Clicking the button pauses/resumes visualisation
PR for https://github.com/iotaledger/explorer/issues/194
> Feat: Support pausing/resuming the visualiser

- client/src/app/routes/Landing.scss
Removed top padding of .feeds-wrapper
Bug fix (css)
PR for https://github.com/iotaledger/explorer/issues/187
> Fix(css): Remove top padding on feeds wrapper

- client/src/app/routes/Landing.scss
- client/src/app/routes/Landing.tsx
- client/src/scss/themes.scss
Performed adjustments as described in the task:
- Added Done button in filters header which closes the modal
- Reordered entries in header
- Aligned header with checkboxes below
- Added an indicator to the filters toggle button showing counter for enabled filters
Fixes https://github.com/iotaledger/explorer/issues/191
- Check look is as requested in proposed design https://www.figma.com/file/j4RLa61iZ18VXwiabeyu9k/IOTA-Explorer-UI?node-id=1706%3A28366
- Check it looks good on both themes
- Close filters button works
> Fix: Add adjustments for filters header and toggle filters button

- client/src/app/routes/Landing.scss
- Reduced height of header banner to 280px
- Adjusted position of sphere images to be similarly positioned as before
- Reduced top padding of header banner on smaller desktops
Fixes https://github.com/iotaledger/explorer/issues/186
Bug fix (css)
- Visual check
> Fix: Reduce min-height of header banner

- api/src/clients/fixerClient.ts
- api/src/initServices.ts
- api/src/models/api/ICurrencyNamesResponse.ts
- api/src/models/clients/fixer/ISymbolsResponse.ts
- api/src/models/db/ICurrencyState.ts
- api/src/routes.ts
- api/src/routes/currency/names/get.ts
- api/src/routes/init.ts
- api/src/services/currencyService.ts
- client/src/app/components/FiatSelector.scss
- client/src/app/components/FiatSelector.tsx
- client/src/app/components/FiatSelectorState.ts
- client/src/app/components/Footer.tsx
- client/src/app/routes/Landing.tsx
- client/src/models/api/ICurrencyNamesResponse.ts
- client/src/models/services/ICurrencySettings.ts
- client/src/services/apiClient.ts
- client/src/services/currencyService.ts
- Added data population request (to Fixer API) which is performed on Services initialisation and stored in currency settings.
- Reworked implementation of FiatSelector.tsx to custom drop-down with currency names as per design [here](https://www.figma.com/file/j4RLa61iZ18VXwiabeyu9k/IOTA-Explorer-UI?node-id=1745%3A28396)
Aims to fix https://github.com/iotaledger/explorer/issues/223
- Currency drop-down displays currencies and selecting works.
> Feat: Re-implement currency drop-down selector

- client/src/app/routes/Landing.tsx
- client/src/models/services/valueFilter.ts
- Fixed Feed Default Filter Values initialisation when switching networks. 
The issues was that `DEFAULT_VALUES_FILTER` was not recomputed when switching from "chrysalis" -> "og". So the filter options where the wrong ones and all the messages were filtered out leaving an empty feed.
Aims to fix https://github.com/iotaledger/explorer/issues/250
Feed now works when switching to Legacy-mainnet and filters display correct values
> Fix(client): Fix feed filter (re)initialisation when switching networks

- client/src/app/App.scss
- client/src/app/App.tsx
The UI and some features of your v2 explorer is highly inspired from [thetangle.org](https://thetangle.org/) but it's never mentioned.
Feature requests also directly ask to copy thetangle.org (eg. #148, #75, #46, #81).
Similarly to [what the Hornet team did](https://github.com/gohornet/hornet/blob/b09279f3ffa3dc28432e7439c1a606c9ceabf8b5/plugins/spa/frontend/src/app/components/Explorer.tsx#L33) for their built-in explorer, this PR adds the mention of thetangle.org in the footer.
> Add inspiration credit

- client/package-lock.json
- client/src/app/components/FiatSelector.scss
- client/src/scss/themes.scss
In this PR i have implemented dark mode for currency dropdown. For this i have changed the color from gray to white of fiat acronym in the dropdown.
This change can be test visually.
> Fix: Change fiat acronym color from gray to white in currency dropdown.

- client/src/app/components/chrysalis/Transaction.tsx
- client/src/app/routes/chrysalis/Addr.tsx
- client/src/models/api/chrysalis/ITransactionsDetailsResponse.ts
- client/src/services/tangleCacheService.ts
- Sorted transactions and "relatedTransaction" (spending ones)
- Lowered MAX_PAGE_SIZE
- Removed a recursive call so we see "batches" data sooner
Transactions are now sorted by descending date "per page". Switching pages triggers fetching of "relatedTransactions" for transactions and sorting. 
Large histories will still have inconsistent sorting "across pages".
Aims to fix https://github.com/iotaledger/explorer/issues/129
Visually
> Fix: Improve transaction history (sorting)

- client/src/app/components/Header.tsx
- client/src/app/components/NetworkSwitcher.scss
- client/src/app/components/NetworkSwitcher.tsx
Network selector design update. Now it looks like this:
Aims to compete https://github.com/iotaledger/explorer/issues/288
Visually.
> Feat: Update network selector headings

- client/src/app/routes/chrysalis/Addr.tsx
- Fix minor issues that sometimes happens when loading transaction history where status in column displays "PendingConflicting" and gets stuck loading (page refresh makes it disappear)
> Fix: Address minor issue with inclusion state for relatedTransactions in Add.tsx

- client/src/app/components/stardust/Output.tsx
- client/src/app/components/stardust/OutputProps.tsx
- client/src/app/components/stardust/OutputState.tsx
- client/src/app/components/stardust/TransactionPayload.tsx
- Display foundry id, alias id and nft id in there respective outputs.
- Add copy button to copy these id's.
- Add link so that on clicking it takes to the corresponding Foundry/Alias/NFT page.
Aims to complete https://github.com/iotaledger/explorer/issues/311
> Feat: Display id's in output on block page.

- client/src/helpers/stardust/transactionsHelper.ts
- Updated `bechAddressFromAddressUnlockCondition` function to build address for foundry output type.
Aims to fix https://github.com/iotaledger/explorer/issues/327
> Fix: Support building address from Foundry Output

- client/src/app/components/MessageTree.scss
- client/src/app/components/MessageTree.tsx
- client/src/app/components/chrysalis/Bech32Address.tsx
- client/src/app/components/chrysalis/Bech32AddressProps.tsx
- client/src/app/components/chrysalis/ReceiptPayload.tsx
- client/src/app/components/chrysalis/Transaction.tsx
- client/src/app/components/chrysalis/TransactionPayload.scss
- client/src/app/components/chrysalis/TransactionPayload.tsx
- client/src/app/routes/chrysalis/Addr.tsx
- Display full address on message page under transaction payload.
- Display full message id's in message tree. For mobile screens the id's will still be truncated as there is not enough space to show the complete id's.
- Display full message id's in transaction history table.
Aims to complete https://github.com/iotaledger/explorer/issues/313
> Feat: Show full Addresses on Message and Address pages

- client/src/helpers/stardust/transactionsHelper.ts
When building the input data from block payload, we displayed the amount from the {transactionId}/included-block API call, which wasn't returning for on input of this block as probably the message that generated the input (as output) was already pruned.
Amount can also be fetched from the actual output fetched directly, and this was done anyway couple lines below.
- Remove the call to included-block
- Used the output fetched directly to find the amount of the input
Aims to fix issue https://github.com/iotaledger/explorer/issues/324
Manually on provided example.
> Fix: Improve amount computing for Inputs

- client/src/app/App.tsx
- client/src/app/components/Feeds.tsx
- client/src/app/components/Header.tsx
- client/src/app/components/HeaderProps.ts
- client/src/app/components/HeaderState.ts
- client/src/app/routes/Visualizer.tsx
- client/src/app/routes/VisualizerRouteProps.ts
- Resolve unnecessary reloading on mode toggle.
- Move mode toggle logic from `App.tsx` to `Header.tsx`.
Aims to complete https://github.com/iotaledger/explorer/issues/317
> Fix: Resolve unnecessary reloading on mode toggle

- client/src/app/components/stardust/AssociatedOutput.tsx
- Remove block string from address found column in `AssociateOutput`.
Aims to fix https://github.com/iotaledger/explorer/issues/360
> Fix: Fix association labels in Associated Outputs Table

- client/src/app/components/stardust/Feature.tsx
- client/src/app/components/stardust/FeatureProps.tsx
- client/src/app/components/stardust/Output.tsx
- client/src/helpers/stardust/nameHelper.ts
- Display immutable features type name correctly.
- Remove `Feature` string from `features` type name.
Aims to fix https://github.com/iotaledger/explorer/issues/376
The change should be visible on the output page of Alias, Foundry or Nft output type.
> Fix: Display correct immutable features type name.

- .github/workflows/client-shimmer-prod.yaml
- .github/workflows/client-shimmer-staging.yaml
With vercel 27.0.0 the output of `vercel ls` is no longer output to stdout what causes the aliasing to fail.
This fixes it
> fixed vercel cli 27.0.0 `ls` bug

- client/src/app/components/FeedInfo.tsx
- Added two decimals precision to FeedInfo "seconds since last" and increased "refresh" rate
Now that milestoneFrequency is 1s on alphanet, doesn't make sense to just show seconds.
Aims to complete https://github.com/iotaledger/explorer/issues/418
> Feat: Improve Feed Info seconds

- client/src/app/components/stardust/NativeToken.tsx
- client/src/app/components/stardust/NativeTokenProps.ts
- client/src/app/components/stardust/NativeTokenState.ts
- client/src/app/components/stardust/Output.tsx
- client/src/app/components/stardust/OutputState.tsx
- Created a separate native token component so that it cannot expand all the native tokens at once.
Aims to fix https://github.com/iotaledger/explorer/issues/430
transactionId = `0x5ad9932fedd598ac76393f49e2296c662abf57c70df4bf67427f76d1f5d27d49`
> Fix: Expand only the clicked native token

- client/src/helpers/stardust/valueFormatHelper.ts
Truncate balance to two decimal places without rounding off so that the user can see the actual balance.
Aims to fix https://github.com/iotaledger/explorer/issues/431
TransactionId = `0xc358097109e37fa268024f66090b1551d18bc7e99041135d494484930fa8dd29`
> Fix: Format balance to two decimal places without rounding off

- client/src/app/routes/stardust/Block.tsx
- client/src/app/routes/stardust/OutputPage.tsx
- client/src/app/routes/stardust/TransactionPage.tsx
- Added redirection to transaction page from `Spent in transaction with ID` on Output page.
- Highlight `Spent in transaction with ID` value.
- Added copy button.
Aims to complete https://github.com/iotaledger/explorer/issues/433
Visit output page that has already been spent.
> Fix: Make "spent in transaction" a link and copiable in OutputPage

- client/src/helpers/stardust/transactionsHelper.ts
- Previously in `transactionHelper.ts` where we compute `unlocks` we only had the functionality to compute unlocks for `SIGNATURE_UNLOCK_TYPE` and `REFERENCE_UNLOCK_TYPE`. Now, we added the functionality for `ALIAS_UNLOCK_TYPE` and `NFT_UNLOCK_TYPE`
Aims to fix https://github.com/iotaledger/explorer/issues/444
**Block Id** = `0x80b3df2fdc2696db2caca49ba6cab2edc32cc7af56fac67c9dba831a09779d7b`.
You will now see the metadata is loading.
> Fix: Include ALIAS and NFT unlock types when computing block signatures

- client/src/services/currencyService.ts
- Remove a confusing regex replace that was causing the issue
I couldn't really understand the point of this "regex + replace" nor why it was in the code.
To me it seams like replacing the point and fraction with a "1" just makes the value incorrect.
What this regex was doing is something like:
`55.00` -> `551`
or 
`55.80` -> `551`
Issue introduced here https://github.com/iotaledger/explorer/pull/103
Aims to fix https://github.com/iotaledger/explorer/issues/445
Manually in code, as it is hard to get the right value to trigger this case.
> Fix: Fix market cap off by factor of 10

- client/src/app/components/stardust/AssociatedOutput.tsx
- client/src/app/components/stardust/AssociatedOutputsTable.scss
- client/src/app/components/stardust/AssociatedOutputsTable.tsx
- Added a column `Amount` in associated outputs table.
- Implemented a toggle on amount to see raw and smr value.
Aims to complete https://github.com/iotaledger/explorer/issues/449
Address = `rms1qq3v8m2hjvflnau3zqm4qw4j9ufmy3qv26ggus28z9wts3n5up82kxhu7m5`
Search this address and you can see the change in associated outputs section.
> Feat: Add amount column in associated outputs

- client/src/app/components/FeedInfo.tsx
- client/src/app/components/FeedsState.ts
- client/src/app/components/chrysalis/Feeds.tsx
- client/src/app/components/stardust/Feeds.tsx
- client/src/app/routes/chrysalis/Landing.tsx
- client/src/app/routes/stardust/Landing.tsx
- Interval counting time since last milestone is not tied to the milestone timestamp anymore
Interval just restarts from 0 every-time the milestone changes
Aims to fix https://github.com/iotaledger/explorer/issues/427
> Fix: Decouple seconds since last milestone from milestone timestamp in FeedInfo

- api/src/models/db/INetwork.ts
- api/src/utils/stardust/stardustTangleHelper.ts
Support configurable "fallback" in API calls
- Added an optional boolean `disableApiFallback' to networks configuration
- If set to true, **and** permanode and node are both configured, fallback will be disabled. Meaning that only permanode will be called, with no call to node on failure.
If permanode is **not** configured, setting the option to true has no effect, as node API will be used anyway.
Aims to complete https://github.com/iotaledger/explorer/issues/452
Manually
- [] New and existing unit tests pass locally …
> Feat: Configurable fallback for API calls

- client/src/app/components/CopyButton.scss
- client/src/app/components/CopyButton.tsx
- client/src/app/components/CopyButtonProps.tsx
- client/src/app/components/CopyButtonState.tsx
- client/src/app/components/chrysalis/Bech32Address.tsx
- client/src/app/components/chrysalis/Output.tsx
- client/src/app/components/chrysalis/TransactionPayload.tsx
- client/src/app/components/stardust/Address.tsx
- client/src/app/components/stardust/AddressBalance.tsx
- client/src/app/components/stardust/AssociatedOutputsTable.scss
- client/src/app/components/stardust/Bech32Address.tsx
- client/src/app/components/stardust/Output.scss
- client/src/app/components/stardust/Output.tsx
- client/src/app/components/stardust/OutputProps.tsx
- client/src/app/components/stardust/TransactionPayload.scss
- client/src/app/routes/IdentityResolver.tsx
- client/src/app/routes/StreamsV0.tsx
- client/src/app/routes/chrysalis/Addr.tsx
- client/src/app/routes/chrysalis/Message.tsx
- client/src/app/routes/og/Address.tsx
- client/src/app/routes/og/Bundle.tsx
- client/src/app/routes/og/Tag.tsx
- client/src/app/routes/og/Transaction.tsx
- client/src/app/routes/stardust/Block.tsx
- client/src/app/routes/stardust/Foundry.tsx
- client/src/app/routes/stardust/NftRegistryDetails.tsx
- client/src/app/routes/stardust/OutputPage.tsx
- client/src/app/routes/stardust/TransactionPage.tsx
- Truncated outputId in Output component (better view in associated outputs and landing)
- Added copy button for output id
- Added optional prop to Output that can be used to display full output ids
- Truncated bech32 addresses nested in Output
- Adjusted scss in Associated outputs and Input/Output components
- Simplified CopyButton code (remove annoying "Copied" message)
Aims to complete https://github.com/iotaledger/explorer/issues/448
> Feat: Truncate output id in Output component

- client/src/app/components/stardust/Output.tsx
- If the alias id hasn't move since it is created then its id will be zero so, we compute BLAKE2b-256 hash for such outputs.
Aims to resolve https://github.com/iotaledger/explorer/issues/387
> Fix: Compute BLAKE2b-256 of the AliasOutput whose id is zero.

- client/src/app/components/stardust/Feeds.tsx
- Add a probe (setInterval) to check for feed being disconnected, if detected it will reset the feed subscription.
This covers the case when on machine sleep, the feed stops streaming with no disconnect event. Now it will resume after 1,5 sec.
Aim to complete https://github.com/iotaledger/explorer/issues/446
> Feat: Add feed re-connect probe

- client/src/app/App.tsx
-  Make first available network config load properly when navigating to base client route
Aims to fix https://github.com/iotaledger/explorer/issues/492
> Fix(client): Fix navigating to base client route

- .github/workflows/api-prod.yaml
- .github/workflows/api-shimmer-prod.yaml
- .github/workflows/api-shimmer-staging.yaml
- .github/workflows/api-staging.yaml
- .github/workflows/bot-prod.yaml
- .github/workflows/client-prod.yaml
- .github/workflows/client-shimmer-prod.yaml
- .github/workflows/client-shimmer-staging.yaml
- .github/workflows/client-staging.yaml
- Updated shimmer client staging workflow to use Node version 16.16.
- Updated shimmer client staging workflow to use Npm version 8.18.
- Updated shimmer api staging workflow to use Node version 16.16.
- Updated shimmer api staging workflow to use Npm version 8.18.
Aims to fix https://github.com/iotaledger/explorer/issues/490
> Fix: GitHub workflows updated to latest node and npm versions

- client/src/app/routes/stardust/AddressPage.tsx
- Display nothing when storage rent is zero on Address Page.
Aims to fix https://github.com/iotaledger/explorer/issues/505
> Fix: Css of storage rent when it is zero

- client/src/app/routes/stardust/landing/ShimmerClaimedUtils.spec.ts
- client/src/app/routes/stardust/landing/ShimmerClaimedUtils.ts
- Don't format to magnitudes
- Format big values to comma separated
- Show glow unit only under 1000 glow
> fix(client): Rework the Shimmer total claimed stat

- client/package-lock.json
- client/package.json
- client/public/index.html
- client/src/index.tsx
- Installed "IBM Plex mono" and "Material icons" as npm package
Fixes https://github.com/iotaledger/explorer/issues/507
Visually
> Fix: Prevent fetching IBM Plex mono font and Material icons from google

- client/src/app/components/stardust/TaggedDataPayload.tsx
- Disable click on tag in Tagged data payload on block page.
> Fix: Disable click on tag in Tagged data payload

- client/src/app/components/chrysalis/MilestonePayload.tsx
- Set milestone state correctly before it redirects to previous/next milestone.
Resolves https://github.com/iotaledger/explorer/issues/544
> Fix: Broken message page navigation.

- .gitignore
- client/src/app/routes/stardust/landing/MilestoneFeed.tsx
Moves "last milestone ticker"  from the feed title to the latest milestone in the feed. This means that the ticker is also not visible until the frontend has fetched at least one milestone.
Aka:
https://user-images.githubusercontent.com/1385611/199050803-6f9f557c-2c2f-45cc-b67c-4c01510fd2ae.mov
Local development instance.
> Feat: Move sec since last milestone ticker to latest entry in the feed

- api/src/models/influx/IInfluxDbCache.ts
- api/src/models/influx/IInfluxTimedEntries.ts
- api/src/routes/stardust/analytics/influx/get.ts
- api/src/services/stardust/influx/influxDbClient.ts
- api/src/services/stardust/influx/influxDbService.ts
- api/src/services/stardust/influx/influxQueries.ts
- client/src/app/routes/stardust/statistics/StatisticsPage.tsx
- client/src/helpers/stardust/statisticsUtils.ts
- client/src/models/api/stardust/influx/IInfluxDailyResponse.ts
Replace avg. active addresses per milestone graph with total active addresses per day
fixes #615 .
> Fix: Replace avg. addresses graph with Total addresses per day

- client/src/app/components/stardust/statistics/ChartTooltip.tsx
Align chart tooltip center and cursor pointer if the tooltip cant fit on either left or right of the cursor pointer and edge of the screen on mobile.  
fixes #619 .
> Fix: Tooltip cutoff on mobile

- api/src/routes/stardust/milestone/stats/get.ts
- client/src/app/routes/stardust/landing/MilestoneFeed.tsx
Check if permanode is configured when retrieving milestone stats.
fixes #603  .
> Fix: Permanode check when retrieving milestone stats

- api/src/services/stardust/influx/influxDbClient.ts
- api/src/services/stardust/influx/influxQueries.ts
- Remove the computation that account for byte cost from the Locked storage stat, and just simply take the query result from one query.
Resolves https://github.com/iotaledger/explorer/issues/627
> chore: Update query for LockedStorage deposit (total) stat

- client/src/app/routes/stardust/Visualizer.scss
- client/src/app/routes/stardust/Visualizer.tsx
Align Visualizer stats to top of the page to be in line with the Pause button
needed for #646 
> Fix: Align Visualizer stats to top of the page [mobile]

- client/src/app/components/chrysalis/QR.scss
- client/src/app/components/stardust/AddressBalance.scss
- client/src/app/components/stardust/AddressBalance.tsx
- client/src/app/components/stardust/Bech32Address.tsx
- client/src/app/routes/stardust/AddressPage.scss
- client/src/app/routes/stardust/AddressPage.tsx
- Make storage balance inline with spendable and conditional balance for desktop screen.
- Display balances vertically for smaller screens with fiat value inline.
Resolves https://github.com/iotaledger/explorer/issues/634
> Feat: Balance section improvements on Address page

- client/src/app/MilestoneFeedAnalytics.tsx
- client/src/app/components/hoc/TabbedSection.tsx
- client/src/app/routes/stardust/landing/MilestoneFeed.tsx
- Make tabs linkable by adding `tab` query to the URL
- Added link from Milestone feed (block/txs numbers) to Referenced Blocks tab on Milestone Block page
resolves #659 .
> Feat: Make Tabs linkable

- client/src/app/routes/chrysalis/Message.tsx
- client/src/app/routes/chrysalis/MessageState.ts
- client/src/helpers/chrysalis/transactionsHelper.ts
- Added a helper function to compute transactionId from transactionPayload for chrysalis.
-  Show transactionId on Message page.
Resolves https://github.com/iotaledger/explorer/issues/623
> Fix: Compute txid on message page for chrysalis.

- client/src/helpers/stardust/transactionsHelper.spec.ts
- client/src/helpers/stardust/transactionsHelper.ts
- Created a function to convert little endian encoded hex to big endian.
- Sort inputs and outputs of transaction payload by index.
Resolves https://github.com/iotaledger/explorer/issues/656
> Fix: Sort transaction payload inputs and outputs by index

- client/src/app/components/stardust/Nft.tsx
- client/src/app/components/stardust/NftMetadataSection.tsx
Adds also the `muted` attribute as otherwise `autoplay` doesn't work on Chromium browsers.
> Auto play and loop NFT vids

- client/package-lock.json
- client/package.json
- client/src/app/components/stardust/Nft.tsx
- client/src/app/components/stardust/NftMetadataSection.tsx
- client/src/app/components/stardust/NftMetadataUtils.tsx
- client/src/app/components/stardust/address/ImagePlaceholder.scss
- client/src/app/components/stardust/address/ImagePlaceholder.tsx
- client/src/helpers/fetchHelper.ts
- client/src/helpers/hooks/useNftMetadataUri.ts
- client/src/helpers/stardust/ipfsHelper.ts
- client/src/index.tsx
- client/src/services/apiClient.ts
- client/src/services/stardust/ipfsClient.ts
- Removed http-ipfs-client lib dependency
- Added minimal ipfs client
- Added `isLoading` flag for fetching nft metadata uri and display loading image placholder when ipfs response is slow.
needed for #679 .
> Feat: Add minimal IPFS client and loading flag for NFT metadata uri

- api/src/routes/stardust/search.ts
- api/src/utils/stardust/searchExecutor.ts
- api/src/utils/stardust/stardustTangleHelper.ts
- api/tsconfig.json
- Search queries that originate from `StardustTangleHelper.search` are now executed in parallel with a `Promise.any` type race (first successful is returned)
Resolves https://github.com/iotaledger/explorer/issues/682
Reviewer:
Please test **ALL** types of searches supported in `SearchExecutor`
> feat(api): Improve search speed 🐇 

- client/src/app/components/stardust/InclusionState.tsx
- client/src/app/components/stardust/block/section/BlockMetadataSection.tsx
- client/src/app/routes/stardust/TransactionPage.tsx
- Header changed to `Inclusion Status`.
- For transactionPayload blocks, if `ledgerInclusionState` is `confirmed` wording changed to "The block is confirmed by a milestone and the transaction successfully mutated the ledger state".
- For transactionPayload blocks, if `ledgerInclusionState` is `conflicting`  wording changed to "The block is confirmed by a milestone but the transaction is conflicting".
- And for `noTransaction` inclusion state wording changed to "The block is referenced by a milestone but there is no value transfer".
Resolves https://github.com/iotaledger/explorer/issues/686
> Fix: Updated wording for block metadata

- api/src/models/api/stardust/ISearchResponse.ts
- api/src/models/api/stardust/ITaggedOutputsRequest.ts
- api/src/models/api/stardust/ITaggedOutputsResponse.ts
- api/src/models/api/stardust/basic/IBasicOutputsResponse.ts
- api/src/routes.ts
- api/src/routes/stardust/output/tagged/get.ts
- api/src/utils/stardust/searchExecutor.ts
- api/src/utils/stardust/searchQueryBuilder.ts
- api/src/utils/stardust/stardustTangleHelper.ts
- client/package-lock.json
- client/src/app/components/hoc/TabbedSection.tsx
- client/src/app/components/stardust/Output.scss
- client/src/app/components/stardust/Unlocks.tsx
- client/src/app/components/stardust/block/payload/TransactionPayload.scss
- client/src/app/routes/stardust/OutputList.scss
- client/src/app/routes/stardust/OutputList.tsx
- client/src/app/routes/stardust/Search.tsx
- client/src/helpers/hooks/useTaggedOutputs.ts
- client/src/models/api/stardust/ISearchResponse.ts
- client/src/models/api/stardust/ITaggedOutputsRequest.ts
- client/src/models/api/stardust/ITaggedOutputsResponse.ts
- client/src/models/api/stardust/basic/IBasicOutputsResponse.ts
- client/src/services/stardust/stardustApiClient.ts
- client/src/services/stardust/stardustTangleCacheService.ts
- Search by tag now also searches Nft outputs
- OutputList page reworked with pagination and TabbedSections (basic/nft)
- OutputList results are backend paginated up to a limit of 100 outputs
⚠️ This needs a chronicle with this https://github.com/iotaledger/inx-chronicle/pull/1171 deployed, otherwise permanode won't return the outputs properly
Resolves https://github.com/iotaledger/explorer/issues/692
> Feat: Improve searching outputs by Tag

- client/src/app/components/stardust/Feature.tsx
Use the `isParticipationMetadataFlag` in Feature that to display Data toggle correctly
fixes #733 .
> Fix: Data Toggle for Participation events  

- client/src/app/components/header/Header.tsx
- client/src/app/routes/stardust/Visualizer.scss
- client/src/app/routes/stardust/Visualizer.tsx
- client/src/helpers/hooks/useVisualizerState.tsx
- client/src/models/api/stardust/feed/IFeedBlockData.ts
- client/src/services/stardust/stardustFeedClient.ts
On the Visualizer page, when you choose a block containing a transaction payload, a list of associated blocks with reattached transactions will be displayed.
fixes #727 .
> Feat: Display blocks with reattached transaction on Visualizer 

- api/src/models/api/stardust/IAliasResponse.ts
- api/src/models/api/stardust/IOutputDetailsResponse.ts
- api/src/models/api/stardust/IResponse.ts
- api/src/models/api/stardust/foundry/IFoundriesResponse.ts
- api/src/models/api/stardust/foundry/IFoundryResponse.ts
- api/src/models/api/stardust/nft/INftDetailsResponse.ts
- api/src/models/api/stats/IMilestoneAnalyticStats.ts
- api/src/routes/stardust/milestone/influx/get.ts
- api/src/utils/stardust/stardustTangleHelper.ts
- client/src/helpers/hooks/useNftDetails.ts
- client/src/models/api/stardust/IAliasResponse.ts
- client/src/models/api/stardust/IOutputDetailsResponse.ts
- client/src/models/api/stardust/IResponse.ts
- client/src/models/api/stardust/foundry/IFoundriesResponse.ts
- client/src/models/api/stardust/foundry/IFoundryResponse.ts
- client/src/models/api/stardust/nft/INftDetailsResponse.ts
- client/src/models/api/stats/IMilestoneAnalyticStats.ts
- client/src/services/stardust/stardustTangleCacheService.ts
Added stardust `IResponse` model with `message` property that contains info message when the requested resource was not found. (eg. No output found)
Previously "Not found" message was return as `error` property which would than get delivered to fronted with status code 400 and get logged in the console.
fixes #705 .
> Fix: Remove 400 responses from console for Alias/Nfts

- client/src/app/components/DataToggle.scss
Added `word-break` instead of `break-all` rule in Data toggle content.
fixes #764 .
> Fix: Word break in Data Toggle component

- api/package-lock.json
- api/package.json
- api/src/routes/stardust/identity/resolution-stardust/get.ts
Update the identity resolver tool to work with the latest `0.7` release.
We have to add the `sdk-wasm` dependency as the identity library requires it. This can lead to the SDK being included twice, for Wasm and for Node.js once `iota-client` is replaced. 
Also the DID example should be changed to `did:iota:rms:0xabe51fb63206a02970378fcc2051884f12d33a39358e4fe8b4999c43d11fae7e` on testnet.
resolve `did:iota:rms:0xabe51fb63206a02970378fcc2051884f12d33a39358e4fe8b4999c43d11fae7e` on testnet
> Update identity tool

- client/src/helpers/hooks/useCurrencyService.ts
Resetting price stats on stardust landing page when switching networks
> Fix: Resetting price stats on stardust landing page

- client/src/app/components/stardust/Unlocks.tsx
Show copy button for signatures in the Unlocks
resolves #792 
> Fix: Show copy button for signatures

- client/src/app/components/stardust/Visualizer/Wrapper.tsx
- client/src/app/routes/stardust/VisualizerDefault.tsx
- client/src/app/types/visualizer.types.ts
- client/src/features/visualizer-threejs/Emitter.tsx
- client/src/features/visualizer-threejs/VisualizerInstance.tsx
- client/src/features/visualizer-threejs/store.ts
- client/src/features/visualizer-webgl/VisualizerWebgl.tsx
- client/src/features/visualizer-webgl/useVisualizerViva.ts
Re-connect the pause button. On pause renderer should stop and useUpdateListener should stop listening for new blocks.
- Feature
Go to visualizer. Press "play" and "pause" buttons. Nodes should to stop and run again in accordance.
> Feat: Reimplement play/pause in Visualizer

- client/src/features/visualizer-threejs/Emitter.tsx
- client/src/features/visualizer-threejs/VisualizerInstance.tsx
- client/src/features/visualizer-threejs/hooks/useBorderPositions.ts
- client/src/features/visualizer-threejs/hooks/useZoomDynamic.ts
- client/src/features/visualizer-threejs/store/config.ts
- client/src/features/visualizer-threejs/store/index.ts
- client/src/features/visualizer-threejs/store/tangle.ts
- client/src/features/visualizer-threejs/useRenderEdges.ts
- client/src/features/visualizer-threejs/useRenderTangle.tsx
Move "running" and "show edges" flags to useConfigStore.
- refactoring
Make sure that everything works as before.
> Refactoring: move "running" and "show edges" flags to useConfigStore.

- api/src/utils/stardust/searchExecutor.ts
- api/src/utils/stardust/stardustTangleHelper.ts
- client/src/app/routes/stardust/Search.tsx
- Fixed searchExecutor to use the correct methods from SDK
- Added `ignoreNodeHealth` to all requests to chronicle as SDK considers it NotHealthy
fixes for #821.
Search address 0x082b58f55715a61e6b3db02374bdf1a3f09c2a836228738b27d2c180f44dcb91740100000000.
Before changes: it shows page 'not found'.
After changes: redirect to `foundry/0x082b58f55715a61e6b3db02374bdf1a3f09c2a836228738b27d2c180f44dcb91740100000000`
> Fix: Search by TokenId

- client/src/features/visualizer-threejs/VisualizerInstance.tsx
- client/src/features/visualizer-threejs/store/tangle.ts
- client/src/features/visualizer-threejs/useRenderTangle.tsx
Reduce initial width of the blocks in the visualizer to look more similar to the design. 
Fixes #904 
> enhancement: polish block sizing

- .gitignore
- api/package-lock.json
- api/package.json
- client/package-lock.json
- client/package.json
- package.json
- setup_nova.sh
- Add temporary convenient setup of local iota-sdk-nova for development
Needs `rust` installed to build SDK
It's hooked into `npm run setup:dev` on root package (takes a while, but only the first time)
You can also run it separately with `npm run setup:sdk-nova-local`
> chore: Add script to setup iota-sdk nova locally

- client/src/features/visualizer-threejs/VisualizerInstance.tsx
- client/src/features/visualizer-threejs/constants.ts
- client/src/features/visualizer-threejs/store/tangle.ts
- client/src/features/visualizer-threejs/utils.ts
Fixes #891 
Improves the shape of the tangle so that not only the Y axis is positioned randomly, but the Z too, and randomize the X axis so blocks travel at different speeds. It also takes into account the starting position of the emitter so that the tangle moves when the emitter moves (for #941)
- Enhancement
Use a custom network to test for 50 and 200 bps. The range of the radius is linear to the min and max blocks per second. For less blocks see mainnet.
> feat: improve radius based on throughput

- api/src/models/api/stardust/chronicle/IAddressBalanceResponse.ts
- client/src/app/routes/stardust/AddressPage.tsx
- client/src/app/routes/stardust/AddressState.ts
- client/src/helpers/hooks/useAddressBalance.ts
- client/src/models/api/stardust/address/IAddressBalanceResponse.ts
Update explorer response to https://github.com/iotaledger/inx-chronicle/issues/1312
Close https://github.com/iotaledger/explorer/issues/925
- [] I have performed a self-review of my …
> feat: replace chronicle balance response `sigLockedBalance` with `availableBalance`

- client/src/app/components/header/Header.tsx
> fix: check for modal message in Header

- client/src/features/visualizer-threejs/constants.ts
- Tweaked parameters to make the Tangle bigger by default
Closes https://github.com/iotaledger/explorer/issues/1038
- [] I have …
> Feat: tweak visualizer zoom

- api/src/models/api/nova/feed/IFeedUpdate.ts
- api/src/services/nova/feed/novaFeed.ts
- client/src/app/routes.tsx
- client/src/features/visualizer-threejs/VisualizerInstance.tsx
- client/src/features/visualizer-threejs/constants.ts
- client/src/models/api/nova/feed/IFeedUpdate.ts
- client/src/services/nova/novaFeedClient.ts
- Sets new Visualizer to be used only on Nova networks
- Listens to `block-metadata` topics and streams updates in novaFeed
- Colours Blocks in the Visualizer based on `TransactionState` 
Closes https://github.com/iotaledger/explorer/issues/1034
> Feat: Support metadata topics in nova visualizer

- api/src/routes.ts
- api/src/routes/chrysalis/transactionhistory/download/post.ts
- api/src/utils/chrysalis/chrysalisTangleHelper.ts
- client/src/app/components/chrysalis/DownloadModal.scss
- client/src/app/components/chrysalis/DownloadModal.tsx
- client/src/app/components/chrysalis/Transaction.scss
- client/src/app/routes/chrysalis/Addr.scss
- client/src/app/routes/chrysalis/Addr.tsx
- client/src/helpers/hooks/useTransactionHistoryDownload.ts
- client/src/services/chrysalis/chrysalisApiClient.ts
Download report in csv for chrysalis
Closes https://github.com/iotaledger/explorer/issues/1109
1. Go to address page.
2. Press on "download" icon.
3. Choose date.
4. Click "Confirm"
Expected result: download zip with csv inside.
> feat: download report for Chrysalis.

- api/src/models/api/nova/ISearchRequest.ts
- api/src/models/api/nova/ISearchResponse.ts
- api/src/routes.ts
- api/src/routes/nova/search.ts
- api/src/services/nova/novaApiService.ts
- api/src/utils/nova/addressHelper.ts
- api/src/utils/nova/searchExecutor.ts
- api/src/utils/nova/searchQueryBuilder.ts
- client/src/app/routes.tsx
- client/src/app/routes/nova/Search.tsx
- client/src/models/api/nova/ISearchRequest.ts
- client/src/models/api/nova/ISearchResponse.ts
- client/src/services/nova/novaApiClient.ts
> feat: add basic nova search

- client/src/features/visualizer-threejs/VisualizerInstance.tsx
- client/src/features/visualizer-threejs/store/tangle.ts
- client/src/features/visualizer-threejs/useRenderTangle.tsx
> feat: update blocks metadata on paused visualizer

- api/src/services/stardust/influx/influxQueries.ts
Close https://github.com/iotaledger/explorer/issues/1101
- …
> fix: lockedStorageDeposit multiplied by 100

- client/src/helpers/stardust/preExpandedConfig.ts
- client/src/helpers/stardust/resolveTransiviteUnlock.ts
- client/src/helpers/stardust/transactionsHelper.ts
Fixes #1104 
`shimmer/transaction/0x02b8488d0cd5ff39d8ade27a73c11e85bbc46171e4479d60f194869d7ebdc7d1`
> refactor: handle multiple unlock types in `getInputsPreExpandedConfig`

- client/src/features/visualizer-threejs/Emitter.tsx
- client/src/features/visualizer-threejs/VisualizerInstance.tsx
- client/src/features/visualizer-threejs/blockPositions.ts
- client/src/features/visualizer-threejs/constants.ts
- client/src/features/visualizer-threejs/interfaces.ts
- client/src/features/visualizer-threejs/store/config.ts
- client/src/features/visualizer-threejs/utils.ts
Fixes #1164 
- Enhancement
The emitter should move quicker or slower depending on the period times.
> feat(visualizer): randomize sinusoid period times

- client/src/app/components/nova/address/AccountAddressView.tsx
- client/src/app/components/nova/address/AddressBalance.scss
- client/src/app/components/nova/address/AddressBalance.tsx
- client/src/app/components/nova/address/AnchorAddressView.tsx
- client/src/app/components/nova/address/Ed25519AddressView.tsx
- client/src/app/components/nova/address/ImplicitAccountCreationAddressView.tsx
- client/src/app/components/nova/address/NftAddressView.tsx
- client/src/helpers/nova/hooks/useAccountAddressState.ts
- client/src/helpers/nova/hooks/useAccountDetails.ts
- client/src/helpers/nova/hooks/useAddressBalance.ts
- client/src/helpers/nova/hooks/useAnchorAddressState.ts
- client/src/helpers/nova/hooks/useAnchorDetails.ts
- client/src/helpers/nova/hooks/useEd25519AddressState.ts
- client/src/helpers/nova/hooks/useImplicitAccountCreationAddressState.ts
- client/src/helpers/nova/hooks/useNftAddressState.ts
- client/src/helpers/nova/hooks/useNftDetails.ts
- client/src/models/api/nova/address/IAddressBalanceResponse.ts
Closes https://github.com/iotaledger/explorer/issues/1074
> feat: Add mana balance to address pages

- client/src/app/components/nova/OutputView.scss
- client/src/app/components/nova/OutputView.tsx
- client/src/helpers/nova/outputUtils.ts
- Added icons (with Tooltip) to OutputView for outputs with "special" unlock conditions
- Added outputUtils with capability of checking if an CommonOutput `isExpired` and `isTimeLocked`
- Color of icon depends if EUC is expired (or timelocked)
Closes https://github.com/iotaledger/explorer/issues/1087
- Need an Output with actual Expiration unlock condition to test this!! (Blocked)
- Need an Output with actual TimeLock unlock condition to test this!! (Blocked)
> feat: Improve expiration and timelock unlock conditions

- client/src/app/components/nova/address/section/AddressPageTabbedSections.tsx
Tabbed section need the "first" tab to be always enabled
- Rearranged the ordering of tabs so that all cases have an enable first tab that can be selected by default
> Fix: Improve rendering of tabbed section initial state

- api/src/routes/networks/get.ts
- api/src/services/stardust/nodeInfoService.ts
- api/src/services/stardust/stardustApiService.ts
- Use circulating supply from inx-supply-tracker in stardust networks if available (fallback to network config value)
Closes https://github.com/iotaledger/explorer/issues/1331
> feat: Use circulating supply from node endpoint

- api/src/models/api/nova/IDelegationByValidatorResponse.ts
- api/src/routes.ts
- api/src/routes/nova/output/delegation/by-validator/get.ts
- api/src/services/nova/novaApiService.ts
- client/src/app/components/nova/address/section/AddressPageTabbedSections.tsx
- client/src/app/components/nova/address/section/account/AccountValidatorSection.tsx
- client/src/helpers/nova/hooks/useAccountAddressState.ts
- client/src/helpers/nova/hooks/useValidatorDelegationOutputs.ts
- client/src/models/api/nova/IDelegationByValidatorResponse.ts
- client/src/services/nova/novaApiClient.ts
- client/tsconfig.json
Closes https://github.com/iotaledger/explorer/issues/1153
> feat: Add delegation outputs to Validator tab of Account page

- .github/workflows/nova-build-temp.yaml
- api/package-lock.json
- client/package-lock.json
- client/src/app/routes/nova/Block.tsx
- setup_nova.sh
Closes https://github.com/iotaledger/explorer/issues/1304
> Feat: Add block cost to block page

- client/src/app/components/nova/OutputView.tsx
- client/src/app/components/nova/UnlockConditionView.tsx
Closes https://github.com/iotaledger/explorer/issues/1379
ts-ignore commets can be removed after https://github.com/iotaledger/iota-sdk/issues/2217 is fixed
> fix: Fix slotIndex field access in Expiration unlock condition

- api/src/services/nova/nodeInfoService.ts
Closes https://github.com/iotaledger/explorer/issues/1377
Because if node info is refreshed, the `latestSlotIndex` used in `outputManaWithDecay` will be correct
> feat: Add periodic updating of NodeInfo for nova

- api/src/models/db/networkType.ts
> chore: add shimmer & iota testnets to valid network types

- api/src/models/api/stardust/IAssociationsResponse.ts
- api/src/routes/stardust/output/associated/post.ts
- api/src/services/stardust/stardustApiService.ts
- api/src/utils/stardust/associatedOutputsHelper.ts
Remove assets from Address Page if expiration time has passed and show them on the Address page for the `expirationReturnAddress`
closes #594 
Native tokens can be tested on shimmer using the address `smr1qqe0adqtuyz2pg4gqf37cu9w0d4znj4dejzz6svw3fhtsmgw08j3g4pgs5a` from the task #594 
Nfts can be tested on Testnet using this output that has expiration unlock condition that has passed: `0xec58cc5a805e979cef0d4e62553957ce43a18c221682d2abf34df91ed0d313e20000`
> Fix: Expired Assets on Address Page

- client/src/helpers/stardust/preExpandedConfig.ts
Add check for alias reference unlock in `preExpandConfig`
closes #1121 
> Fix: Alias reference unlock in preExpandConfig

- client/src/app/components/stardust/address/section/association/AssociatedOutputsUtils.ts
- client/src/models/api/stardust/IAssociationsResponse.ts
`AssociationType` model needs to be aligned in api and client.
Introduced in https://github.com/iotaledger/explorer/pull/1394 
Closes https://github.com/iotaledger/explorer/issues/1411
> fix: Align api and client AssociationType model

- client/src/app/components/nova/ContextInputView.tsx
- client/src/app/components/nova/block/section/TransactionMetadataSection.tsx
- client/src/app/routes/nova/Block.tsx
- client/src/app/routes/nova/FoundryPage.tsx
- client/src/app/routes/nova/TransactionPage.tsx
Closes https://github.com/iotaledger/explorer/issues/1399
> feat: Display account bech32 address instead of account Id

- client/src/app/components/nova/OutputView.scss
- client/src/app/components/nova/OutputView.tsx
- client/src/app/routes/nova/EpochPage.scss
- client/src/features/visualizer-vivagraph/components/KeyPanel.scss
- client/src/scss/layout.scss
Page `Output`
Page `Epoch`
Page `Visualizer`
Closes #1391 
Open pages in mobile view.
> feat: polish mobile ui.

- client/Dockerfile
- client/nginx/wasm.conf
This PR adds a config file that will tell Nginx to send `.wasm` files with the `Content-Type` as `application/wasm` instead of `application/octet-stream`. This allows us to use [streaming compilation](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiateStreaming_static), which may help performance with page loading. It also resolves this warning:
```
`WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:
TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
```
Additionally, when the explorer is proxied through Cloudflare, the application/wasm also lets …
> fix: WASM MIME type in Nginx config

- client/src/app/components/chrysalis/TransactionPayload.scss
- client/src/app/components/stardust/Output.scss
- client/src/app/routes/nova/TransactionPage.scss
> styles: fix output amount breaking into two lines

- client/src/app/routes.tsx
- client/src/app/routes/nova/NftRedirectRoute.tsx
Closes https://github.com/iotaledger/explorer/issues/1439
> feat: Add Nft redirect route (Nova)

- client/src/app/components/nova/StatusPill.scss
- client/src/features/visualizer-vivagraph/Visualizer.scss
- client/src/features/visualizer-vivagraph/definitions/constants.ts
- client/src/scss/variables.scss
> feat: improve block colors in visualizer nova

- client/src/app/routes/nova/OutputPage.tsx
- client/src/helpers/nova/hooks/useAddressBalance.ts
Closes https://github.com/iotaledger/explorer/issues/1433
> fix: Show mana balance for genesis outputs

- client/src/app/components/nova/address/section/account/AccountValidatorSection.scss
- client/src/app/components/nova/address/section/delegation/DelegationSection.scss
- client/src/app/components/nova/address/section/delegation/DelegationSection.tsx
- client/src/app/lib/ui/enums/DelegationOutputsTableHeadings.enum.ts
- client/src/app/lib/ui/enums/DelegationsTableHeadings.enum.ts
- client/src/helpers/nova/hooks/useGenerateDelegationsTable.ts
> Fix: Polish Delegation section

- api/src/models/db/networkType.ts
- client/src/app/AppUtils.tsx
- client/src/helpers/networkHelper.ts
- client/src/models/config/networkType.ts
> chore: Add nova new network type

- client/src/app/App.tsx
- client/src/app/AppUtils.tsx
- client/src/app/routes/nova/landing/Landing.tsx
- client/src/helpers/nova/networkInfo.ts
> fix: add label to nova landing

- README.md
- client/src/app/App.scss
- client/src/app/App.tsx
- client/src/app/AppUtils.tsx
- client/src/app/routes.tsx
- client/src/app/routes/stardust/landing/Landing.tsx
- package-lock.json
Closes https://github.com/iotaledger/explorer/issues/1495
> Explorer deprecation
