iotaledger/explorer

client/package-lock.json
Syncs lockfile as it is out of date (missing a dependency of `fsevents`)
- Chore
N/A
=> chore(client): Sync lockfile

.gitignore, api/.dockerignore, api/DEPLOYMENT.md, api/Dockerfile, client/.dockerignore, client/DEPLOYMENT.md, client/Dockerfile
Adds a Dockerfile for the client web application. It will allow us to run it as part of the Tangle Installer Package with Docker. 
Run the Docker locally. 
=> Add Dockerfile for the client application and Docker deploy documentation

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml
Adds CodeQL security and quality scanning
Workflow runs successfully
=> feature(ci): Add CodeQL scanning

.github/CONTRIBUTING.md
Minor fix to incorrect links on MD
=> Fix links on CONTRIBUTING.md

api/src/clients/coinGeckoClient.ts, api/src/models/api/IMarketGetResponse.ts, api/src/models/clients/coinGecko/ICoinsMarketChartResponse.ts, api/src/models/db/IMarket.ts, api/src/routes/market/get.ts, api/src/services/currencyService.ts, client/src/app/routes/Markets.tsx, client/src/app/routes/MarketsState.ts, client/src/models/api/IMarketGetResponse.ts
Added day data to market statistics API and frontend
=> Added day data to markets

client/src/app/components/Header.scss
Header on mobile was cut off on left side. 
Btw this is my first PR to an open source project ever. Sorry in advance if I have done something completely wrong :)
Tested manually
=> Fix: header mobile cut off on left side

client/src/app/components/identity/IdentityHistory.tsx, client/src/app/components/identity/tree/IdentityTree.tsx, client/src/app/components/identity/tree/IdentityTreeItem.scss, client/src/app/components/identity/tree/IdentityTreeItem.tsx, client/src/app/components/identity/tree/IdentityTreeItemProps.ts, client/src/app/routes/IdentityResolver.tsx, client/src/app/routes/IdentityResolverState.ts
Following changes to Identity Resolver:
- Fixes diff button styling.
- Fixes wrong tree structure if last integration message contains diff messages.
- Improves timestamp format.
- Bug fix (a non-breaking change)
Locally
=> Fix diff button styling

client/src/app/components/identity/tree/IdentityTreeItem.scss
=> change opacity value for fade animation

client/src/app/components/MessageTree.tsx
=> Fix scroll to message tree

.github/ISSUE_TEMPLATE/create-task.yml
This PR adds a task creation template.
=> chore: create a task creation template

client/src/app/routes/IdentityResolver.scss, client/src/app/routes/IdentityResolver.tsx
This PR aims to solve the second part of #116  (adapt the latest DID implementations).
This PR closes #116
=> Feat: Adapt latest DID implementations

client/src/scss/themes.scss
=> Fix: Navbar bg color in Firefox is too transparent

client/src/app/components/Header.scss
=> Fix: Refine padding for small devices

client/src/app/components/MessageTangleState.tsx
Milestone index is now highlighted 
This PR aims to close #161 
=> Fix highlighted milestone

client/src/app/components/identity/IdentityJsonCompare.tsx
Rename toggle buttons to Doc and Msg
This PR aims to close #159
=> Fix: Update toggle buttons title

client/src/app/components/identity/IdentityJsonCompare.scss, client/src/app/components/identity/IdentityJsonCompare.tsx, client/src/scss/themes.scss
Add red and green background and refine +/- color
This PR aims to close #158
=> Fix: CSS message comparison missing in Identity Resolver

client/src/app/components/SearchInput.tsx
=> Fix: Clear search field when a search has been done

client/src/app/routes/IdentityResolver.tsx, client/src/app/routes/chrysalis/Addr.tsx, client/src/app/routes/chrysalis/Indexed.tsx, client/src/app/routes/chrysalis/Message.tsx
This PR aims to resolve:
1.  #141  
2.  #142  
=> Fix: Removed info icon from General / Replaced dots icon with info icon

client/src/app/routes/Landing.scss
Fix view to be responsive in all browsers and sizes
This PR aims to close #132
=> Fix: Landing page resize (Safari)

client/src/app/components/identity/tree/IdentityTreeItem.tsx
This PR fixes an in the identity resolver, with diff messages not being correctly detected in the compare dropdown.
Tested locally with current and fixed code.
=> Fix: identity diff detection

client/src/app/components/MessageTree.tsx
This PR sims so resolve:
#180 
Find some message with no children
=> Fix: displaying Children title in Message tree

api/package-lock.json, api/package.json
Update to `0.5.0-dev.4` version of identity. There was a regression where errors for faulty DIDs changed unexpectedly. `0.5.0-dev.4` restores the pre 0.5 behavior.
Test locally with faulty DIDs.
=> Fix: update to latest version of identity

client/src/app/components/Header.tsx
Closes https://github.com/iotaledger/explorer/issues/135.
N/A
=> docs (client): update network descriptions in the header

client/src/app/components/DataToggle.scss
Set a max height of 400px and a scrollbar when needed.
This PR aims to close #179
=> Fix: Limit JSON payload height

client/src/app/components/Switcher.scss
Minor fix of Switcher toggle css
Visual confirmation
PR for https://github.com/iotaledger/explorer/issues/194
=> Fix: Improve css of Switcher toggle button

client/src/app/routes/Landing.scss
Reduced feed items header padding
Bug fix (css)
PR for https://github.com/iotaledger/explorer/issues/189
=> Fix(css): Reduce feed items header padding

client/src/app/routes/Landing.tsx, client/src/scss/layout.scss, client/src/scss/section.scss
Added padding to "Latest Messages" text
PR for https://github.com/iotaledger/explorer/issues/188
=> Fix: Add padding to "Latest Messages" text

client/src/app/routes/Landing.scss
Decreased item element in feed top/bottom padding
Bug fix (css)
PR for https://github.com/iotaledger/explorer/issues/190
=> Fix(css): Change feed item top padding

client/src/app/components/Footer.tsx
=> Feat/ Remove facebook link

client/src/app/routes/Landing.scss
Reduced max width transaction feed to 960px
Fixes https://github.com/iotaledger/explorer/issues/192
Bug fix (css)
Visual check
=> Fix: Reduce max width transaction feed

client/src/app/components/chrysalis/QR.scss, client/src/app/components/chrysalis/QR.tsx
Added a label "Scan the address QR code to send payment" under QR code image visible on Address page.
Fixes https://github.com/iotaledger/explorer/issues/147
- Visually
=> Feat: Add label under QR code

client/src/app/routes/Landing.scss, client/src/app/routes/Landing.tsx, client/src/scss/layout.scss
=> Fix: Remove 'confirmations per second' indicator

client/src/app/components/Pagination.scss, client/src/app/components/Pagination.tsx, client/src/app/components/PaginationProps.ts, client/src/app/components/PaginationState.tsx, client/src/app/routes/chrysalis/Addr.tsx, client/src/scss/layout.scss
This PR aims to fix:
[#222 ](https://github.com/iotaledger/explorer/issues/222)
Tested on addresses with large number of pages. 
ex. `/mainnet/addr/iota1qzcu634e3my9q8dp4pd2nn5unffwzln89d43syf2qst5vyj9rfe4jrmfep6`
=> Fix: Refine pagination

.github/ISSUE_TEMPLATE/config.yml
Update the issue template config file to reflect the following changes:
1. Link to new features / enhancements on GitHub discussions;
2. Link to General Feedback on GitHub discussions.
Chore
N/A
=> chore: update issue template config

.github/ISSUE_TEMPLATE/bug_report.yml
This PR updates the `label(s)` in bug report template to match the latest label we have for bug reports. 
Chore
N/A
=> chore: update labels in bug report template

api/package-lock.json, api/package.json, api/src/routes/identity/diff/get.ts, api/src/routes/identity/history/get.ts, api/src/routes/identity/resolution/get.ts, api/src/utils/identityHelper.ts, client/src/helpers/identityHelper.ts, client/src/models/identity/IIdentityDocument.ts
Adopt to the latest version of identity. The document structure and API changed in anticipation of the 0.5.0 release (https://github.com/iotaledger/identity.rs/releases/tag/v0.5.0-dev.5).
New example DID: `did:iota:8jYcEGiNYUWcSdEtjCAcS97G58qq1VrWzW7M57BsHymz`
Ran through resolutions of legacy DIDs an current DIDs locally.
- [] New and existing unit tests …
=> Integrate latest identity version

api/src/utils/stardust/searchQueryBuilder.ts, api/src/utils/stardust/stardustTangleHelper.ts
- Refactored the searchApi logic by moving checks of the supplied query string into new SearchQueryBuilder
- Add support for searching by stardust specific criteria
Aims to solve https://github.com/iotaledger/explorer/issues/256
=> Feat: Add stardust specific search

client/Dockerfile
Updated Dockerfile for client
Node 16 + newer Alpine Image. Some adjustments for nginx (`conf.d` -> `http.d`)
=> updated dockerfile

client/src/app/components/FiatSelector.scss, client/src/app/components/FiatSelector.tsx, client/src/app/components/Header.scss, client/src/app/components/SearchInput.scss
=> Feat: Improve dropdown fiat selector position, correct alignment

client/src/app/routes/stardust/Visualizer.tsx
- Fix some issues in Visualizer stardust version
Aims to improve https://github.com/iotaledger/explorer/issues/241
Visualizing
=> Fix: Update Visualizer for Stardust

api/src/clients/fixerClient.ts
Updated the fixer API endpoint to the spec of apilayer site, instead of the fixer.io docuementation
- Deleted server storage
- Deleted browser local storage
- Refresh
=> Feat: Update fixerClient API endpoint

client/src/app/routes/chrysalis/Addr.scss, client/src/app/routes/chrysalis/Addr.tsx
- Added disclaimer about inconsistency of sort when we have more than one page of history
=> Feat: Add disclaimer transaction history sort

client/src/app/components/Pagination.tsx, client/src/app/routes/chrysalis/Addr.tsx
Fix pagination range  for small number of pages
=> Fix: Pagination range for small number of pages

api/src/routes/stardust/milestone/get.ts, api/src/utils/stardust/searchQueryBuilder.ts, api/src/utils/stardust/stardustTangleHelper.ts, client/src/app/components/chrysalis/ReceiptPayload.tsx, client/src/app/components/stardust/Address.tsx, client/src/app/components/stardust/Output.tsx, client/src/app/components/stardust/OutputProps.tsx, client/src/app/components/stardust/ReceiptPayload.tsx, client/src/app/components/stardust/TransactionPayload.tsx, client/src/app/components/stardust/UnlockCondition.tsx, client/src/app/routes/chrysalis/Addr.tsx, client/src/app/routes/stardust/Addr.tsx, client/src/app/routes/stardust/AddrState.tsx, client/src/helpers/chrysalis/bech32AddressHelper.ts, client/src/helpers/chrysalis/transactionsHelper.ts, client/src/helpers/stardust/bech32AddressHelper.ts, client/src/helpers/stardust/transactionsHelper.ts, client/src/models/api/stardust/IOutput.ts
- Update searches for stardust
- Improve data in outputs on UI
- Refactor 
- Remove unused code
Aims to complete **https://github.com/iotaledger/explorer/issues/293**
Manually
=> Fix: Update searches on stardust

client/src/app/routes/stardust/Message.tsx, client/src/app/routes/stardust/MessageState.ts, client/src/helpers/stardust/transactionsHelper.ts
Display transaction id when search from message id on message page.
Aims to complete https://github.com/iotaledger/explorer/issues/296
=> Fix: Display TransactionId on Message page.

client/src/app/components/stardust/Nft.scss, client/src/app/components/stardust/Nft.tsx, client/src/app/routes/stardust/AddressPage.scss, client/src/app/routes/stardust/Alias.tsx, client/src/scss/themes.scss
- Implement dark mode for assets and nfts card section in Address page.
- Change text for State Index in Alias page.
- Make Nft Id clickable.
Aims to complete https://github.com/iotaledger/explorer/issues/315
=> Fix: Dark mode and font issues

api/src/models/api/stardust/ISearchResponse.ts, api/src/utils/stardust/stardustTangleHelper.ts, client/src/app/App.tsx, client/src/app/routes/NftRouteProps.ts, client/src/app/routes/stardust/Nft.tsx, client/src/app/routes/stardust/NftState.tsx, client/src/app/routes/stardust/Search.tsx, client/src/helpers/stardust/bech32AddressHelper.ts, client/src/models/api/stardust/ISearchResponse.ts, client/src/scss/themes.scss, client/src/services/stardust/stardustTangleCacheService.ts
- Add Nft Address page.
- Display native tokens of the nft.
Aims to complete https://github.com/iotaledger/explorer/issues/319
=> feat: Nft address page

.github/ISSUE_TEMPLATE/bug_report.yml, client/src/app/App.tsx, client/src/app/components/Header.tsx, client/src/app/components/HeaderProps.ts, client/src/app/routes/Visualizer.tsx, client/src/app/routes/VisualizerRouteProps.ts
- Merge main branch into dev branch.
- Resolve conflicts.
=> Merge main branch into dev branch.

client/src/models/api/stardust/ISearchResponse.ts, client/src/services/stardust/stardustTangleCacheService.ts
- Fix broken navigation when move back from foundry to address page.
- Fix cache for associated outputs.
Aims to fix https://github.com/iotaledger/explorer/issues/356
=> Fix: Broken page navigation in browser

api/src/utils/stardust/stardustTangleHelper.ts, client/src/app/App.tsx, client/src/app/components/stardust/Feature.tsx, client/src/app/components/stardust/FeatureProps.tsx, client/src/app/components/stardust/FeatureState.tsx, client/src/app/components/stardust/Output.tsx, client/src/app/components/stardust/OutputProps.tsx, client/src/app/components/stardust/UnlockCondition.tsx, client/src/app/components/stardust/UnlockConditionProps.tsx, client/src/app/components/stardust/UnlockConditionState.tsx, client/src/app/routes/SearchState.ts, client/src/app/routes/stardust/OutputPage.scss, client/src/app/routes/stardust/OutputPage.tsx, client/src/app/routes/stardust/OutputPageProps.ts, client/src/app/routes/stardust/Search.tsx, client/src/helpers/stardust/transactionsHelper.ts
- Added a dedicated output page (for search by outputID)
- Fix issue in stardustTangleHelper
Aims to close https://github.com/iotaledger/explorer/issues/370
=> Feat: Add output page

client/src/app/components/stardust/AssociatedOutputsTable.scss, client/src/app/components/stardust/AssociatedOutputsTable.tsx, client/src/app/components/stardust/Feature.tsx, client/src/app/components/stardust/Output.scss, client/src/app/components/stardust/Output.tsx, client/src/app/components/stardust/UnlockCondition.tsx, client/src/app/routes/stardust/OutputPage.scss, client/src/app/routes/stardust/OutputPage.tsx
- Display output id in outputs.
- Fix memory leak warning in associated output table.
Aims to fix https://github.com/iotaledger/explorer/issues/358
=> Feat: Display output id in output

api/src/models/api/stardust/IAssociatedOutputsResponse.ts, api/src/routes/stardust/output/associated/post.ts, api/src/utils/stardust/associatedOutputsHelper.ts, client/src/app/components/Tooltip.scss, client/src/app/components/Tooltip.tsx, client/src/app/components/stardust/AssociatedOutput.tsx, client/src/app/components/stardust/AssociatedOutputsTable.scss, client/src/app/components/stardust/AssociatedOutputsTable.tsx, client/src/models/api/stardust/IAssociatedOutputsResponse.ts
- Grouped associated outputs by output Id
- Added a tooltip to display "additional" associations in AssociatedOutputsTable on mouse hover
- Refactor
Manually
=> Feat: Group Associated Outputs

.github/workflows/api-shimmer-prod.yaml, .github/workflows/api-shimmer-staging.yaml, .github/workflows/client-shimmer-prod.yaml, .github/workflows/client-shimmer-staging.yaml
Adds workflows for Shimmer explorer in `dev` branch
=> Add Shimmer Explorer workflows

.github/workflows/api-shimmer-prod.yaml, .github/workflows/api-shimmer-staging.yaml, .github/workflows/client-shimmer-prod.yaml, .github/workflows/client-shimmer-staging.yaml
Adds workflows for Shimmer explorer in `stardust` branch
=> Add Shimmer Explorer workflows [stardust]

.github/workflows/api-shimmer-prod.yaml, .github/workflows/api-shimmer-staging.yaml
fixed the config.json filename in the workflows for API deployment
=> fix config.json filename in workflows for API

client/src/app/components/chrysalis/Feeds.tsx, client/src/app/components/stardust/Feeds.tsx, client/src/app/routes/Landing.scss, client/src/app/routes/chrysalis/Landing.tsx
- Merge main into stardust
- Fix files after merge to be in line with `main`
Aims to complete https://github.com/iotaledger/explorer/issues/364
=> Feat: Harmonize main landing page metrics

client/src/app/components/Pagination.scss, client/src/app/components/footer/ShimmerFooter.scss, client/src/app/routes/stardust/AddressPage.scss, client/src/app/routes/stardust/AddressPage.tsx, client/src/app/routes/stardust/Landing.scss
- Fix mobile ui minor issues.
Aims to fix https://github.com/iotaledger/explorer/issues/404
Visually
=> Fix: Improve UI consistency on mobile devices

client/src/app/routes/stardust/Visualizer.tsx
- Update Shimmer visualizer info label. `MPS` to `BPS` and `CMPS` to `CBPS`.
Aims to complete https://github.com/iotaledger/explorer/issues/408
Visually.
=> Feat: Update visualizer info labels.

client/src/app/components/stardust/history/TransactionHistory.scss, client/src/app/components/stardust/history/TransactionHistory.tsx, client/src/scss/themes.scss
Aims to complete 
https://github.com/iotaledger/explorer/issues/415
https://github.com/iotaledger/explorer/issues/414
=> Fix: Improve Transaction History (on address page)

client/src/app/components/stardust/Input.tsx, client/src/app/components/stardust/Output.scss, client/src/app/components/stardust/Output.tsx, client/src/app/components/stardust/TransactionPayload.scss, client/src/app/components/stardust/TransactionPayload.tsx, client/src/app/components/stardust/TransactionPayloadProps.tsx, client/src/app/components/stardust/Unlocks.tsx, client/src/app/routes/stardust/Block.tsx, client/src/app/routes/stardust/BlockState.ts, client/src/app/routes/stardust/TransactionPage.tsx, client/src/app/routes/stardust/TransactionPageState.ts, client/src/helpers/stardust/transactionsHelper.ts, client/src/models/api/stardust/IInput.ts, client/src/models/api/stardust/IOutput.ts
- Updated the view style of the TransactionPayload "from" part to also show the Outputs that are consumed as inputs, using the Output.tsx nested view component
- Add the Transaction Unlocks into a dedicated component
Aims to complete https://github.com/iotaledger/explorer/issues/393
=> Feat: Transaction payload Inputs rework

client/src/app/routes/stardust/Block.tsx, client/src/app/routes/stardust/TransactionPage.tsx
- Resolve linting errors from explorer client.
=> Fix: Resolve linting errors

api/src/utils/stardust/stardustTangleHelper.ts, client/src/app/routes/stardust/AddressPage.tsx
- Use Chronicle (first with node fallback) for all indexer calls also
Aims to complete https://github.com/iotaledger/explorer/issues/451
Needs testing
=> Feat: Use Chronicle for indexer calls

client/src/app/components/stardust/AssociatedOutput.tsx
- Display number of days/month/year passed from created date in associated outputs table.
Aims to complete https://github.com/iotaledger/explorer/issues/450
=> Feat: Added time passed since the output created in associated outputs table

.github/workflows/client-shimmer-prod.yaml, .github/workflows/client-shimmer-staging.yaml
- Adjust client shimmer staging/prod workflow for new client config
=> chore: Adjust client shimmer staging/prod workflow for new client config

client/src/app/components/stardust/AddressBalance.scss, client/src/app/components/stardust/AddressBalance.tsx, client/src/app/components/stardust/MilestonePayload.tsx
- Fix milestone payload metadata display.
- Fix styling of conditional balance when it is zero and alignment.
Aims to fix https://github.com/iotaledger/explorer/issues/474 and https://github.com/iotaledger/explorer/issues/479
=> Fix: Milestone payload metadata display and conditional balance styling.

api/src/models/db/INetwork.ts, api/src/services/stardust/chronicleService.ts
- Added need of JWT configure for Chronicle analytics requests
Aims to complete https://github.com/iotaledger/explorer/issues/494
Locally
=> Feat(api): Support JWT auth for chronicle analyics requests

client/public/index.html, client/src/app/routes/stardust/AddressPage.tsx, client/src/app/routes/stardust/Alias.tsx
- Updated client html meta tag for Shimmer Explorer
- Also fixed Storage deposit label on Address page
Aims to complete https://github.com/iotaledger/explorer/issues/506
=> Chore: Update explorer metatag shimmer

README.md, api/CHANGELOG.md, api/package-lock.json, api/package.json, client/CHANGELOG.md, client/package-lock.json, client/package.json
- Updated Explorer to `v3.0.0`
- Updated required node version
- Updated changelog
Resolves https://github.com/iotaledger/explorer/issues/482
=> chore: Update Explorer packages versions

.github/workflows/client-prod.yaml, .github/workflows/client-shimmer-prod.yaml, .github/workflows/client-shimmer-staging.yaml, .github/workflows/client-staging.yaml
- Added api URL config (env.js) script in github workflows for clent-staging and client-prod
=> Chore: Add Api URL config to staging and prod workflows

client/src/helpers/stardust/nameHelper.ts
=> Fix Typo on Storage Deposit

client/src/app/components/stardust/TaggedDataPayload.tsx
Remove leftover unused variables from TaggedDataPayload.tsx
=> Fix: Remove unused variables from TaggedDataPayload.tsx

client/src/app/components/stardust/MilestonePayload.tsx, client/src/app/routes/stardust/Block.tsx
- Move parents in milestone view to metadata.
- Make parents in milestone clickable.
Fixes https://github.com/iotaledger/explorer/issues/503
=> Fix: Clickable parents in milestone view.

client/src/app/routes/stardust/NftRegistryDetails.tsx
I replaced the NFT registry text with a hint that it isn't implemented yet(? 😅).
Not tested
=> Add tmp placeholder for NFT registry

client/src/app/components/chrysalis/TransactionPayload.tsx, client/src/app/components/chrysalis/TransactionPayloadState.tsx
Added amount display toggle for inputs in Transaction payload section on Message page.
fixes #513 .
=> Fix: Amount display toggle

client/src/app/components/stardust/AssociatedOutputs.scss, client/src/app/components/stardust/AssociatedOutputs.tsx, client/src/app/components/stardust/AssociationSection.scss, client/src/app/components/stardust/AssociationSection.tsx
- Added css for association labels on dark mode.
Resolves https://github.com/iotaledger/explorer/issues/550
=> Fix: Add color to association label for dark mode

client/src/app/routes/stardust/landing/AnalyticStats.scss, client/src/app/routes/stardust/landing/AnalyticStats.tsx
- Make sure info boxes for Analytic stats are symmetrically displayed if some stats are missing
=> Fix(css): Fix Analytic stats info boxes css

api/package-lock.json, api/package.json, api/src/models/api/stardust/ITransactionHistoryDownloadBody.ts, api/src/models/api/stardust/ITransactionHistoryDownloadResponse.ts, api/src/models/api/stardust/ITransactionHistoryRequest.ts, api/src/models/api/stardust/ITransactionHistoryResponse.ts, api/src/routes.ts, api/src/routes/stardust/transactionhistory/download/post.ts, api/src/services/stardust/chronicleService.ts, api/src/utils/apiHelper.ts, client/src/app/components/Modal.tsx, client/src/app/components/stardust/DownloadModal.scss, client/src/app/components/stardust/DownloadModal.tsx, client/src/app/components/stardust/history/TransactionHistory.scss, client/src/app/components/stardust/history/TransactionHistory.tsx, client/src/helpers/fetchHelper.ts, client/src/models/api/IRawResponse.ts, client/src/services/apiClient.ts, client/src/services/stardust/stardustApiClient.ts
- Implemented fetch of transaction history based on period-to-date (how far back to fetch from current date) supporting:
- 1 month
- 6 months
- 1 year
- all
- Added support for zipping the resulting JSON data and triggering a download of the zip file
Resolves https://github.com/iotaledger/explorer/issues/548
=> Feat: Implement basic TX history download based on period-to-date

client/src/app/components/stardust/statistics/StackedBarChart.scss, client/src/app/components/stardust/statistics/StackedBarChart.tsx, client/src/app/routes/stardust/statistics/BarChart.tsx, client/src/app/routes/stardust/statistics/StatisticsPage.tsx
- Added a StackedBarChart
- Generify charts to data agnostic
=> Feat: Add stacked bar chart

client/src/app/components/DataToggle.scss, client/src/app/components/chrysalis/TransactionPayload.tsx, client/src/app/components/stardust/Feature.tsx, client/src/app/components/stardust/NativeToken.tsx, client/src/app/components/stardust/Output.scss, client/src/app/components/stardust/Output.tsx, client/src/app/components/stardust/TransactionPayload.scss, client/src/app/components/stardust/TransactionPayload.tsx, client/src/app/components/stardust/UnlockCondition.tsx, client/src/app/components/stardust/Unlocks.tsx, client/src/scss/card.scss, client/src/scss/layout.scss, client/src/scss/themes.scss
- Added left border for all the sections of inputs and outputs.
- Fix spacing between different sections.
Resolves https://github.com/iotaledger/explorer/issues/576 https://github.com/iotaledger/explorer/issues/581
=> Fix: Spacing of inputs and outputs in transaction section

client/src/app/routes/stardust/OutputPage.scss, client/src/app/routes/stardust/OutputPage.tsx, client/src/helpers/stardust/nameHelper.ts, client/src/helpers/stardust/valueFormatHelper.tsx, client/src/scss/section.scss
Highlight Genesis block Id on Output page.
fixes #578 .
=> Fix: Highlight Genesis block Id

api/src/models/api/stardust/ITransactionHistoryDownloadBody.ts, api/src/routes/stardust/transactionhistory/download/post.ts, api/src/services/stardust/chronicleService.ts, client/src/app/components/stardust/DownloadModal.scss, client/src/app/components/stardust/DownloadModal.tsx, client/src/scss/themes.scss, client/src/services/stardust/stardustApiClient.ts
- Added date picker to select period to download transaction history.
- Added an info message for date picker.
Resolves https://github.com/iotaledger/explorer/issues/579
=> Feat: Add date picker to download transaction history.

api/src/models/clients/coinGecko/ICoinsMarketsResponse.ts, api/src/services/currencyService.ts, client/src/app/components/FiatSelector.tsx, client/src/app/components/FiatValue.tsx, client/src/app/components/header/Header.tsx, client/src/app/routes/stardust/Block.tsx, client/src/app/routes/stardust/landing/AnalyticStats.scss, client/src/app/routes/stardust/landing/InfoBox.scss, client/src/app/routes/stardust/landing/InfoBox.tsx, client/src/app/routes/stardust/landing/Landing.scss, client/src/app/routes/stardust/landing/Landing.tsx, client/src/helpers/networkHelper.ts, client/src/services/currencyService.ts
Added Shimmer price stats to Landing page.
fixes #553 .
=> Feat: Shimmer price stats

client/src/app/routes/stardust/landing/Landing.tsx
Ordering of milestones after navigating back to landing page.
fixes #635 .
=> Fix: Ordering of milestones on Landing page

client/src/app/components/hoc/TabbedSection.scss
Add scrollable functionality on tabbed section header for mobile view.
needed for https://github.com/iotaledger/explorer/issues/646
=> Fix: Scrollable Tabbed section header

client/src/app/components/stardust/Asset.tsx, client/src/app/components/stardust/AssetsTable.scss, client/src/app/components/stardust/Nft.scss, client/src/app/components/stardust/Nft.tsx
Truncated Native token and Nft names on Address Page sections.
needed for #652 
- [] I have commented my code, particularly in …
=> Chore: Truncate Native token and Nft names

client/src/app/components/stardust/AddressBalance.scss
Removed some CSS introduced via https://github.com/iotaledger/explorer/commit/c65a1467c55f0ab782130dcabf6cf76d31dbe680
=> Fix black balance color

client/src/app/components/stardust/BlockPayloadSection.tsx, client/src/app/components/stardust/Output.scss, client/src/app/components/stardust/TransactionPayload.scss, client/src/app/components/stardust/TransactionPayloadProps.tsx, client/src/app/components/stardust/Unlocks.tsx, client/src/app/routes/stardust/BlockState.ts, client/src/app/routes/stardust/TransactionPageState.ts, client/src/helpers/stardust/transactionsHelper.ts
- Display all 4 unlock types in unlocks component.
Resolves https://github.com/iotaledger/explorer/issues/655
=> Fix: Display all four unlocks types in Unlocks component

client/src/app/components/stardust/NftMetadataSection.scss, client/src/app/components/stardust/NftMetadataSection.tsx
Looks a little bit cleaner (and justifying content on desktop looks better than mobile)
| PR  | Previous |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/1385611/221136247-3a79c4f4-0875-4eea-ad97-676c7a6954af.png) | ![image](https://user-images.githubusercontent.com/1385611/221136345-17ae3563-5db9-4b54-bd36-a645be6eda86.png)  |
=> Break on words and justify description

client/src/app/routes/stardust/TransactionPage.scss, client/src/app/routes/stardust/TransactionPage.tsx
- Tabify sections on Transaction page.
- Truncate ids on Transaction page.
Resolves https://github.com/iotaledger/explorer/issues/678
=> Feat: Tabify sections on Transaction page

client/src/app/components/stardust/address/section/AddressPageTabbedSections.tsx, client/src/app/components/stardust/address/section/nft/Nft.tsx, client/src/app/components/stardust/address/section/nft/NftMetadataSection.tsx, client/src/app/components/stardust/address/section/nft/NftMetadataUtils.tsx, client/src/helpers/hooks/useTokenRegistryNftCheck.ts
Add loading image placehloder to nft metadata section
=> Fix: Add loading image placehloder to nft metadata section

client/src/app/routes.tsx, client/src/app/routes/stardust/NftRedirectRoute.tsx
added nft route with component that redirects to Address page
fixes #714 .
=> Fix: Add Nft Route Redirect

client/src/helpers/hooks/useNftMetadataUri.ts
Reset NFT uri in useNftMetadataUri hook.
fixes #720 .
=> Fix: Reset NFT uri

.gitignore, api/package-lock.json, api/package.json, api/src/clients/fixerClient.ts, api/src/index.ts, api/src/initServices.ts, api/src/logger.ts, api/src/routes/init.ts, api/src/routes/stardust/transactionhistory/download/post.ts, api/src/services/chrysalis/chrysalisFeedService.ts, api/src/services/currencyService.ts, api/src/services/legacy/zmqService.ts, api/src/services/stardust/chronicleService.ts, api/src/services/stardust/influx/influxDbClient.ts, api/src/services/stardust/stardustFeedService.ts, api/src/services/stardust/stardustStatsService.ts, api/src/utils/apiHelper.ts, api/src/utils/legacy/legacyTangleHelper.ts, api/src/utils/stardust/stardustTangleHelper.ts
- Added winston
- Replaced current console.log usages with logger calls
Resolves https://github.com/iotaledger/explorer/issues/693
=> Feat(logging): Add and configure api logging

api/src/services/stardust/influx/influxQueries.ts
- Fix Shimmer claimed influx queries for latest chronicle changes
Resolves https://github.com/iotaledger/explorer/issues/729
=> Fix(influx): Fix Shimmer claimed influx queries for latest chronicle changes

client/src/app/components/stardust/address/section/nft/NftMetadataUtils.tsx
Add image/webp to supported NFT images
Resolves https://github.com/iotaledger/explorer/issues/724
=> Feat: Add image/webp to supported NFT images

api/src/models/api/IFeedSubscribeRequest.ts, api/src/models/api/stardust/feed/IFeedUpdate.ts, api/src/routes/feed/subscribe.ts, api/src/routes/feed/unsubscribe.ts, api/src/services/stardust/feed/stardustFeed.ts, client/src/helpers/hooks/useBlockFeed.ts, client/src/helpers/hooks/useVisualizerState.tsx, client/src/models/api/stardust/feed/IFeedBlockData.ts, client/src/models/api/stardust/feed/IFeedSubscribeRequest.ts, client/src/models/api/stardust/feed/IFeedUnsubscribeRequest.ts, client/src/models/api/stardust/feed/IFeedUpdate.ts, client/src/services/stardust/stardustFeedClient.ts
client/api
- Split subscribe/unsubscribe on stardust to `block`/`milestone`
Resolves https://github.com/iotaledger/explorer/issues/731
=> Feat: Split stardust feed for Landing and Visualizer

client/src/helpers/hooks/useVisualizerState.tsx
- Increased Visualizer feed probe threshold for 'slower' networks
Resolves https://github.com/iotaledger/explorer/issues/753
=> Fix: Increase Visualizer feed probe threshold

api/src/services/stardust/influx/influxQueries.ts
- Replaced _value suffix in influx query fields with _amount
Resolves https://github.com/iotaledger/explorer/issues/757
=> Fix: Update influx queries for latest

client/src/app/routes/stardust/Visualizer.scss, client/src/app/routes/stardust/Visualizer.tsx, client/src/helpers/hooks/useVisualizerState.tsx
Added improvements for Vizualizer Info panel on mobile:
- Check marks for block status on info panel
- Dropdown for reattached blocks
fixes #749 .
=> Fix: Improve Info panel on Visualizer page

client/src/app/components/stardust/address/section/AddressPageTabbedSections.tsx, client/src/app/components/stardust/address/section/voting/VotingEvent.tsx, client/src/app/components/stardust/address/section/voting/VotingSection.scss, client/src/app/components/stardust/address/section/voting/VotingSection.tsx, client/src/app/components/stardust/address/section/voting/VotingUtils.ts, client/src/app/routes/stardust/AddressState.ts, client/src/helpers/hooks/useParticipationEventDetails.ts, client/src/services/stardust/stardustApiClient.ts
Added voting event filtering by event status
resolves #732 .
=> Feat: Add Voting event filtering based on event status

api/src/utils/stardust/searchExecutor.ts, api/src/utils/stardust/searchQueryBuilder.ts, api/src/utils/stardust/stardustTangleHelper.ts, client/src/app/components/stardust/foundry/TokenInfoSection.tsx, client/src/app/routes/stardust/AddressState.ts, client/src/app/routes/stardust/Search.tsx, client/src/helpers/stardust/valueFormatHelper.tsx
- Fetching data from Node first and Chronicle as a fallback if no data was retrieved from the node.
- Adds the formatNumberWithCommas to improve the readability of large numbers in the UI.
- Refine tag search to allow utfb8 and hex search and added a limit of 64 characters 
resolves #762 .
=> [Task]: Stardust API calls fallback

api/CHANGELOG.md, api/package-lock.json, api/package.json, client/CHANGELOG.md, client/package-lock.json, client/package.json
Bump explorer version to 3.2.0
=> Chore: Bump explorer version to 3.2.0

client/src/features/visualizer-threejs/VisualizerInstance.tsx
(Fix) Improve behaviour when changing tabs. Current plan is to stop the stream (pause) and have it paused when you come back to tab.
Open visualizer. Go to another tab. Visualizer should stop.
=> Feat: Pause stream when window is out of focus

client/src/app/AppUtils.tsx, client/src/app/components/header/Header.tsx, client/src/app/routes/chrysalis/Landing.tsx
Resolves https://github.com/iotaledger/explorer/issues/796
=> Chore: Update chrysalis mainnet landing

client/src/features/visualizer-threejs/VisualizerInstance.tsx, client/src/features/visualizer-threejs/store.ts, client/src/features/visualizer-threejs/worker/entities/BPSCounter.ts
For changing view depends on BPS we need to know real BPS of our tangle. As value that we get from external service has some delays.
Detect real BPS.
Log value `bps` from store.
=> Feat: Add a BPS tracker to Visualizer

client/src/features/visualizer-threejs/Emitter.tsx, client/src/features/visualizer-threejs/VisualizerInstance.tsx, client/src/features/visualizer-threejs/constants.ts, client/src/features/visualizer-threejs/utils.ts
Improve UI for low bps.
- feature
Change in hornet spammer BPS from 50 to 5;
=> Feat: Dynamic placement of nodes based on current BPS

client/src/app/components/stardust/Visualizer/Wrapper.tsx, client/src/features/visualizer-threejs/Emitter.tsx, client/src/features/visualizer-threejs/VisualizerInstance.tsx, client/src/features/visualizer-threejs/store.ts, client/src/features/visualizer-threejs/useRenderEdges.ts, client/src/features/visualizer-threejs/useRenderTangle.tsx
- Added support for rendering edges in the tangle, controllable with a checkbox on UI
=> Feat: Add render edges of tangle

client/src/app/components/stardust/Visualizer/SelectedFeedInfo.tsx, client/src/app/components/stardust/Visualizer/Wrapper.tsx, client/src/app/routes/stardust/Visualizer.scss, client/src/features/visualizer-threejs/VisualizerInstance.tsx, client/src/features/visualizer-threejs/hooks/useMouseMove.ts, client/src/features/visualizer-threejs/store/tangle.ts, client/src/features/visualizer-threejs/useRenderTangle.tsx
When user click on node - show detail info.
- feature
Click to shape and see details about block.
=> Feat: Show block metadata on click

.github/workflows/docker-deployment.yaml
adds a docker build workflow that also deploys on the explorer server
=> chore: Add docker deployment workflow

client/src/app/components/chrysalis/ReceiptPayload.tsx, client/src/app/components/stardust/block/payload/ReceiptPayload.tsx, client/src/app/components/stardust/block/payload/milestone/MilestonePayload.tsx
fixes #803.
Open milestone with message. Make sure that css not broken.
Example of UI that you have to see:
=> Feat: Fix payload block receipt payloads

api/src/routes/stardust/milestone/influx/get.ts, api/src/services/stardust/influx/influxDbClient.ts, api/src/services/stardust/influx/influxDbService.ts, api/src/services/stardust/influx/influxQueries.ts, client/src/helpers/hooks/useBlockFeed.ts
fixes #848
- when milestone feed don't get analytic value from cache - request it from db
- when switch between network - reset timer for latest milestone
=> Fix: Improve Milestone Feed consistency

.gitignore, client/package.json, client/script/postinstall.sh, client/src/index.tsx
* Add a client "postinstall" bash script and initialization of wasm from client.
This allows better scaling when multiple wasm files are used on the client
=> feat: Add support for multiple SDK (wasm) versions on client

client/src/features/visualizer-threejs/VisualizerInstance.tsx, client/src/features/visualizer-threejs/constants.ts, client/src/features/visualizer-threejs/store/tangle.ts, client/src/features/visualizer-threejs/useRenderTangle.tsx
Adds colors for confirmed blocks. FIxes #903 
=> feat: add confirmed colors to visualizer three

.husky/pre-push, README.md, package-lock.json, package.json
fixes #850, fixes #849
Add root scripts for install and run project.
Run `npm i && npm run setup:dev` for installing all packages.
Run `npm run dev` to run api and client at the same time.
Push your changes. When you push your changes, husky will check tsc and lint.
=> Chore: Add husky hook and convenience scripts in root folder

.github/workflows/nova-docker-deploy.yaml
Adds new workflow
Close https://github.com/iotaledger/explorer/issues/874
=> ci: deploy nova branch

setup_nova.sh
- Fix setup_nova script to work on linux
=> chore: Fix setup_nova script to work on linux

client/src/app/App.tsx, client/src/app/AppUtils.tsx, client/src/app/components/nova/OutputView.tsx, client/src/helpers/nova/networkInfo.ts, client/src/services/nova/novaFeedClient.ts
- Added a NetworkInfo state (zustand) and hooked it into App initialisation
=> Feat: Add nova network context on client

client/src/features/visualizer-threejs/Emitter.tsx, client/src/features/visualizer-threejs/constants.ts, client/src/features/visualizer-threejs/utils.ts
=> feat: add sinusoidal wave motion to the emitter

api/src/initServices.ts, api/src/models/api/nova/INodeInfoResponse.ts, api/src/models/api/nova/IOutputDetailsResponse.ts, api/src/models/api/nova/feed/IFeedUpdate.ts, api/src/routes/node/info.ts, api/src/services/nova/feed/novaFeed.ts, api/src/services/nova/nodeInfoService.ts, api/src/services/nova/novaApi.ts
Silence SDK unresolved on CI (nova)
=> Chore: Silence SDK unresolved on CI (nova)

client/src/app/components/identity/DIDResolver.tsx, client/src/helpers/hooks/useResolvedDID.ts, client/src/index.tsx
Add absolute path for wasm files
fixes #948 
=> Fix: Crash with Basic auth credentials in the URL

client/src/app/components/footer/ExplorerVersion.scss, client/src/app/components/footer/ExplorerVersion.tsx, client/src/app/components/footer/Footer.scss, client/src/app/components/footer/Footer.tsx, client/src/app/components/footer/ShimmerFooter.scss, client/src/app/components/footer/ShimmerFooter.tsx, client/vite-env.d.ts, client/vite.config.ts
- Injected the Explorer client version for package.json in frontend (footer)
Resolves https://github.com/iotaledger/explorer/issues/967
=> feat: Show Explorer client version from package.json on the Footer

.github/workflows/build-images.reusable.yaml, .github/workflows/create-draft-release.reusable.yaml, .github/workflows/release-production.yaml, .github/workflows/release-staging.yaml
Fixes #1011
Depends on #1026 & #1019 
Private repo
=> feat: add changelog to github draft release

.github/workflows/build-images.reusable.yaml, .github/workflows/create-draft-release.reusable.yaml, .github/workflows/release-production.yaml, .github/workflows/release-staging.yaml
=> feat: add reusable workflow to create a release

client/src/app/AppUtils.tsx
=> hotfix: ShimmerEVM Testnet Explorer link typo

client/src/app/components/header/Header.tsx, client/src/app/components/header/HeaderDropdown.tsx
Fixes #1042 
Fixes #1041 
Theme change should work in the first attempt.
Dropdowns in mobile should be the same as in desktop
=> fix: update theme correctly and show dropdowns correctly

client/src/features/visualizer-threejs/Emitter.tsx
- Hides reference scene elements in Visualizer
Closes https://github.com/iotaledger/explorer/issues/1039
=> chore: Hide reference scene elements in Visualizer

client/src/app/AppUtils.tsx, client/src/app/components/nova/address/ImplicitAccountCreationAddressView.tsx, client/src/app/routes/nova/AddressPage.tsx, client/src/helpers/nova/addressHelper.ts, client/src/helpers/nova/hooks/useImplicitAccountCreationAddressState.ts
Closes https://github.com/iotaledger/explorer/issues/1071
=> feat: Add ImplicitAccountCreation address page case

client/src/features/visualizer-threejs/wrapper/KeyPanel.scss, client/src/features/visualizer-threejs/wrapper/KeyPanel.tsx
Change colors and shape for legend.
Closes #1048
- [] New and existing unit tests pass …
=> enhancement: update legend for visualizer

client/src/app/routes/nova/Search.tsx
=> hotfix: undefined params

client/src/app/routes/stardust/landing/AnalyticStats.tsx
=> fix: "Rewards claimed" stats for Shimmer

client/src/app/components/nova/landing/LandingEpochSection.scss, client/src/app/components/nova/landing/LandingEpochSection.tsx, client/src/app/routes.tsx, client/src/app/routes/nova/landing/Landing.scss, client/src/app/routes/nova/landing/Landing.tsx, client/src/helpers/nova/hooks/useCurrentEpochProgress.ts, client/src/helpers/nova/hooks/useNovaTimeConvert.ts, client/src/helpers/nova/novaTimeUtils.spec.ts, client/src/helpers/nova/novaTimeUtils.ts
Closes https://github.com/iotaledger/explorer/issues/1061
=> Feat: Add Epoch section on Landing

api/src/models/api/nova/foundry/IFoundriesRequest.ts, api/src/models/api/nova/foundry/IFoundriesResponse.ts, api/src/routes.ts, api/src/routes/nova/account/foundries/get.ts, api/src/services/nova/novaApiService.ts, client/src/app/components/nova/address/section/AddressPageTabbedSections.tsx, client/src/app/components/nova/address/section/account/AccountFoundriesSection.scss, client/src/app/components/nova/address/section/account/AccountFoundriesSection.tsx, client/src/helpers/nova/hooks/useAccountAddressState.ts, client/src/helpers/nova/hooks/useAccountControlledFoundries.ts, client/src/models/api/nova/foundry/IFoundriesRequest.ts, client/src/models/api/nova/foundry/IFoundriesResponse.ts, client/src/services/nova/novaApiClient.ts
=> Feat: Add Foundries tab to Account address page

client/src/app/components/stardust/statistics/InfluxChartsTab.tsx
Closes https://github.com/iotaledger/explorer/issues/1100
=> feat: Show shimmer claiming related graphs only on Shimmer

.github/workflows/pr-test-check.yaml
Only for client as there are not tests on api
Closes https://github.com/iotaledger/explorer/issues/1105
=> chore: Include client test run in pull-request CI checks

api/src/initServices.ts, setup_nova.sh
Fixes #1143 
- Breaking change
=> fix: update client to the latest iota-sdk changes

client/src/helpers/hooks/useAddressHistory.ts
=> hotfix: always hidden tx history tab in address page

client/src/features/visualizer-threejs/VisualizerInstance.tsx, client/src/features/visualizer-threejs/wrapper/Wrapper.tsx
Temporarily remove the edges checkbox
=> chore: remove edges checkbox

client/package.json
Add stylelint to pre commit in client
Enhancement
=> chore: add stylelint to pre-commit

client/src/app/components/nova/landing/LandingEpochSection.tsx, client/src/app/routes.tsx, client/src/app/routes/nova/EpochPage.tsx, client/src/assets/modals/nova/epoch/main-header.json, client/src/helpers/nova/hooks/useEpochProgress.ts
=> Feat: Add Epoch Page

api/src/models/influx/nova/IInfluxDbCache.ts, api/src/models/influx/nova/IInfluxTimedEntries.ts, api/src/routes/nova/analytics/influx/daily/get.ts, api/src/services/nova/influx/influxQueries.ts, api/src/services/nova/influx/influxServiceNova.ts, client/src/app/components/nova/statistics/InfluxChartsTab.tsx, client/src/helpers/nova/hooks/useChartsState.ts, client/src/helpers/nova/statisticsUtils.ts, client/src/models/api/nova/influx/IInfluxDailyResponse.ts
=> Feat: Add daily transactions statistics

api/src/models/influx/nova/IInfluxDbCache.ts, api/src/models/influx/nova/IInfluxTimedEntries.ts, api/src/routes/nova/analytics/influx/daily/get.ts, api/src/services/nova/influx/influxQueries.ts, api/src/services/nova/influx/influxServiceNova.ts, client/src/app/components/nova/statistics/InfluxChartsTab.tsx, client/src/helpers/nova/hooks/useChartsState.ts, client/src/helpers/nova/statisticsUtils.ts, client/src/models/api/nova/influx/IInfluxDailyResponse.ts
=> Feat: Add Daily Outputs Statistics

client/src/app/components/nova/address/section/native-tokens/AssetsTable.tsx
Native Token Feature plain to instance
=> Fix: Native Token Feature plain to instance

api/src/utils/stardust/searchExecutor.ts
- Fix alias with DID search race condition in searchExecutor
Closes https://github.com/iotaledger/explorer/issues/949
Searching for aliasId with/without "did..." prefix
=> fix: Fix alias with DID search race condition in searchExecutor

client/src/helpers/hooks/useAddressHistory.ts
Open page http://localhost:3000/shimmer/addr/smr1qpypv9zssx73nswcdwacj5vrqcr2lpat9y39yk4tm8kekaaqcfy66nuj3nt
in firefox.
Take a look list of transactions. They have to be sorted from newest to oldest.
=> fix: transactions for firefox sort properly.

client/src/app/components/Hero.scss, client/src/app/components/Hero.tsx, client/src/app/components/Table.scss, client/src/app/components/nova/landing/LandingEpochSection.scss, client/src/app/components/nova/landing/LandingSlotSection.scss, client/src/app/routes/nova/landing/Landing.scss, client/src/app/routes/nova/landing/Landing.tsx
=> feat: add landing stats to hero

client/src/app/lib/ui/interfaces/NovaButton.interface.ts, client/src/app/lib/ui/interfaces/index.ts
=> fix: remove debris to fix client build

client/src/features/visualizer-vivagraph/GraphContext.tsx, client/src/features/visualizer-vivagraph/VisualizerInstance.tsx, client/src/features/visualizer-vivagraph/components/SelectedFeedInfo.tsx, client/src/features/visualizer-vivagraph/components/Wrapper.tsx, client/src/features/visualizer-vivagraph/definitions/constants.ts, client/src/features/visualizer-vivagraph/hooks/useFeed.ts, client/src/features/visualizer-vivagraph/lib/helpers.ts, client/src/features/visualizer-vivagraph/store/tangle.ts, client/typings/vivagraph/index.d.ts
Highlight connection and search result on node click and change value in search bar.
Closes #1271
- feature
1. Click to node. Expected result: connected nodes and lines are highlighted.
2. Change value in search bar. Expected result: nodes with matched id hightlighted.
=> feat: Add node selection & search

api/package-lock.json, api/package.json, api/src/routes/stardust/identity/resolution-stardust/get.ts
Use the current version of IOTA Identity in the API, allowing automatic pulls of SemVer compatible 1.X versions.
Mirrors: https://github.com/iotaledger/explorer/pull/1295
=> chore: update stardust identity version in API

client/src/app/routes/stardust/landing/AnalyticStats.tsx
=> hotfix: shimmer claimed stats after fixing configured circulating supply

client/src/app/components/nova/landing/LandingSlotSection.scss, client/src/app/components/nova/landing/SlotTableCell.tsx, client/src/app/lib/ui/enums/SlotTableHeadings.enum.ts, client/src/app/routes/nova/landing/Landing.scss, client/src/helpers/nova/hooks/useGenerateSlotsTable.ts
Improve table heading in slots table 
Improve container to look like figma
Improve slot status pill to not make table jump
Fixes #1329 
=> chore: rename `From/To` to `Timestamp` in Slots Table

client/src/app/components/nova/address/AddressBalance.tsx, client/src/helpers/nova/hooks/useAddressBalance.ts, client/src/models/api/nova/address/IAddressBalanceResponse.ts
Fixes #1199 
alphanet/addr/rms1pzkvnshkrkjx4n4grchsythcdlu4m9q6p0ps0ktxanc3erd2mzjy52ce6ee
alphanet/addr/rms1zrl935e5lrnuwmlfdqez679dnja774gtlny3gq4ahpeuf4ktqulh55gfkqe
=> feat: add mana decay balance to address page

client/src/app/routes/nova/EpochPage.tsx, client/src/helpers/nova/hooks/useEpochProgress.ts, client/src/helpers/numberHelper.ts
Fix Epoch0 view and add info for future epochs.
Future epoch view:
Epoch 0 view:
Open Epoch 0 by address `<network>/epoch/0`. Make sure that is doesn't info from current epoch.
Expected result: Epoch 0 shows as finished.
Open future Epoch.
Expected result: 
- from/to with year
- Time remaining: Not started
- Progress: 0%
- Registration end: display nothing (-)
- Starts in
=> fix: epoch page

client/src/app/AppUtils.tsx, client/src/app/components/footer/ExplorerVersion.scss, client/src/app/components/footer/Footer.scss, client/src/app/components/footer/Footer.tsx, client/src/app/components/header/Header.tsx, client/src/app/components/hoc/TabbedSection.scss, client/src/app/components/nova/landing/LandingEpochSection.scss, client/src/app/components/nova/landing/SlotTableCell.tsx, client/src/index.scss, client/src/scss/themes.scss
=> feat: general polishing

client/src/app/routes/nova/Block.tsx
Closes https://github.com/iotaledger/explorer/issues/1350
=> fix: Fix navigating between blocks retains transactionId from state

client/src/app/components/nova/address/section/account/AccountBlockIssuanceSection.tsx, client/src/app/components/nova/address/section/account/AccountValidatorSection.tsx
Closes https://github.com/iotaledger/explorer/issues/1353
=> Chore: Polish address page

client/src/app/components/nova/TableCell.tsx, client/src/app/components/nova/landing/LandingEpochSection.tsx, client/src/app/components/nova/landing/LandingSlotSection.scss, client/src/app/components/nova/landing/LandingSlotSection.tsx, client/src/app/lib/ui/enums/CommitteeTableHeadings.enum.ts, client/src/app/routes/nova/EpochPage.scss, client/src/app/routes/nova/EpochPage.tsx, client/src/helpers/nova/hooks/useGenerateCommitteeTable.ts, client/src/helpers/nova/hooks/useGenerateSlotsTable.ts, client/src/helpers/nova/novaTimeUtils.ts
=> Chore: Polish Epoch page

client/src/app/components/nova/OutputView.tsx, client/src/app/components/nova/TableCell.tsx, client/src/app/lib/ui/enums/ValidatorsTableHeadings.enum.ts, client/src/helpers/nova/hooks/useGenerateCommitteeTable.ts, client/src/helpers/nova/hooks/useGenerateValidatorsTable.ts
=> enhancement: polish units and copy validators address

client/src/features/visualizer-vivagraph/Visualizer.scss, client/src/features/visualizer-vivagraph/components/KeyPanel.tsx, client/src/features/visualizer-vivagraph/definitions/constants.ts, client/src/features/visualizer-vivagraph/hooks/useFeed.ts
Closes #1277
Over visualizer for Nova and check the color of edges.
=> feat: polish visualizer

client/src/app/components/NetworkSwitcher.scss, client/src/app/components/NetworkSwitcher.tsx, client/src/helpers/networkHelper.ts, client/src/models/config/networkType.ts
Closes #1406 
Open navigation and take a look order.
=> feat: Improve network list

client/src/helpers/stardust/valueFormatHelper.spec.ts, client/src/helpers/stardust/valueFormatHelper.tsx
Closes #1197
This fix also works for `dev` branch.
Test different types of numbers in tests `valueFormatHelper.spec.ts`.
=> feat: fix transaction history number formatting

client/src/app/components/nova/address/AddressBalance.tsx, client/src/app/components/nova/address/section/account/AccountBlockIssuanceSection.tsx, client/src/helpers/bigDecimal.ts, client/src/helpers/stardust/valueFormatHelper.spec.ts
Closes https://github.com/iotaledger/explorer/issues/1382
=> Fix: Block issuance credit

.github/workflows/nova-build-temp.yaml, api/package-lock.json, client/package-lock.json, client/src/app/components/nova/OutputView.tsx, client/src/app/components/nova/UnlockConditionView.tsx, client/src/helpers/nova/outputUtils.ts, setup_nova.sh
Closes https://github.com/iotaledger/explorer/issues/1395
=> Fix: Remove unneeded ts-expect-error

api/src/utils/stardust/associatedOutputsHelper.ts
=> Fix: Association endpoints returning empty array

client/src/app/components/nova/ContextInputView.tsx
=> Fix: Change account link to addr

client/src/app/components/nova/OutputView.tsx, client/src/app/components/nova/address/section/account/AccountBlockIssuanceSection.tsx, client/src/app/routes/nova/EpochPage.tsx, client/src/app/routes/nova/SlotPage.tsx, client/src/helpers/nova/hooks/useGenerateSlotsTable.ts
1. Avoid showing copy button on undefined values
2. Remove `?tab=Txs` from slot link
3. Avoid breaking into two lines in the block page too
Fixes #1432 
=> fix: quick polishes

client/src/index.tsx
Fixes #1460 
http://example:example@localhost:3000/mainnet
=> fix: basic authentication error with react

client/src/app/routes/nova/SlotPage.tsx
=> feat: Add Epoch index to Slot page

client/src/app/AppUtils.tsx
CLose https://github.com/iotaledger/explorer/issues/1416
- …
=> feat: add IOTA EVM Testnet explorer link to navbar

client/src/app/components/nova/OutputView.scss, client/src/app/components/nova/OutputView.tsx
=> fix: output amount CSS on mobile (nova)

client/src/app/components/nova/StatusPill.scss
=> styles: improve text color for failed status pill in nova

client/src/app/AppUtils.tsx
Close https://github.com/iotaledger/explorer/issues/1374
- [] My code follows the contribution guidelines for this …
=> feat: add IOTA EVM explorer link

client/src/app/components/nova/address/section/account/AccountBlockIssuanceSection.tsx
Close https://github.com/iotaledger/explorer/issues/1485
- [] My code follows the contribution guidelines for this …
=> fix: public key hash typo
